### ISSUE TITLE
New website scraper request: Moulinex.fr

### ISSUE THREAD

**Issue by Katosheiri** [hhursev/recipe-scrapers#1006]
Could you please add the website moulinex.fr ? Here are a few examples of recipes :

https://www.moulinex.fr/recette/detail/PRO/Velout%C3%A9%20de%20pommes%20de%20terre%20et%20courgettes%20au%20Kiri/2119330

https://www.moulinex.fr/recette/detail/PRO/Couscous/v1/recipes/123432

https://www.moulinex.fr/recette/detail/PRO/Rougail%20saucisses/v1/recipes/108104

Thanks :)

**Comment by SANTASLAYERS** [comment]
Working on this now!
