### ISSUE TITLE
NoSchemaFoundInWildMode: recipe-scrapers exception: No Recipe Schema found at None.

### ISSUE THREAD

**Issue by Bardo-Konrad** [hhursev/recipe-scrapers#1007]
The issue is that I converted cookbooks in pdf to html and read them using 

```
ort = "cookbook.html"
f = open(ort,"r",encoding="UTF-8")
html = f.read()
f.close()

scraper = scrape_html(html=html)
print(scraper)
```
And I get the following

**Pre-filing checks**

- [ x] I have searched for open issues that report the same problem
- [ x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

None

...

**The results you expect to see**

Recipes

**The results (including any Python error messages) that you are seeing**
    scraper = scrape_html(html=html)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Logs\Anaconda\envs\p311\Lib\site-packages\recipe_scrapers\__init__.py", line 695, in scrape_html
    raise NoSchemaFoundInWildMode(org_url)
recipe_scrapers._exceptions.NoSchemaFoundInWildMode: recipe-scrapers exception: No Recipe Schema found at None.

**Comment by jayaddison** [comment]
Sorry; this library can only scrape a single recipe at a time from the HTML retrieved from public recipe websites.

**Comment by Bardo-Konrad** [comment]
So if I separated the recipes it could work?

**Comment by jayaddison** [comment]
It's unlikely to work with generic PDF-to-HTML conversion software, but in theory it is possible, if the conversion software produces HTML that contains valid [`schema.org` recipe metadata](https://schema.org/Recipe).

**Comment by Bardo-Konrad** [comment]
> It's unlikely to work with generic PDF-to-HTML conversion software, but in theory it is possible, if the conversion software produces HTML that contains valid [`schema.org` recipe metadata](https://schema.org/Recipe).

That is not the case, for sure. Isn't there a regex part that detects recipes and extracts them in a robust way in the code?

**Comment by jayaddison** [comment]
There's no generic regex for that, no - the typical workflow is that the domain-name from the recipe's URL is matched against our available scrapers, and if one is found, then it implements logic for each of the different fields (`title`, `ingredients`, `prep_time`, ...).  Fortunately, many of them can look that data up directly in the `schema.org` metadata -- and if not, they can navigate the HTML to find the relevant information.

**Comment by Bardo-Konrad** [comment]
> and if not, they can navigate the HTML to find the relevant information.

How?
