### ISSUE TITLE
Extruct breaking due to lxml breakage 

### ISSUE THREAD

**Issue by disconsented** [hhursev/recipe-scrapers#1045]
I'd been running into the issue described here https://github.com/scrapinghub/extruct/issues/215 

Adding `lxml>=5.0.0,<5.1.0` to `requirements-dev.txt` and reinstalling via pip resolved this issue for me.

**Comment by jayaddison** [comment]
Thanks @disconsented :+1: 

A question / possible adjustment: is there a reason to exclude v5.1.0 in the version range?  I think the breaking change introduced here was in v5.1.1 of `lxml` (eba79343d0e7ad1ce40169f60460cdd4caa29eb3).

**Comment by jtcimba** [comment]
Confirming that uninstalling and reinstalling with @disconsented 's specified versions worked for me

**Comment by michael-genson** [comment]
FYI - there is a [new version of extruct](https://github.com/scrapinghub/extruct/releases/tag/v0.17.0) out which fixes this
