### ISSUE TITLE
[Add] Felix.kitchen scraper

### ISSUE THREAD

**Issue by vabene1111** [hhursev/recipe-scrapers#1063]
Another site with nice recipes and no schema

https://felix.kitchen/2024/04/03/eier-curry-indisch-burmesisch-tomaten-curryblaetter/
https://felix.kitchen/2024/04/10/pasta-penne-chorizo-tomaten-spinat-pinienkerne/
https://felix.kitchen/2024/04/07/piccata-milanese-schnitzel-parmesan-safran-risotto-petersilie/

**Comment by mlduff** [comment]
@vabene1111 are you planning on implementing this yourself or can I take it?

**Comment by vabene1111** [comment]
I am very busy with rewriting tandoors frontend so I would love someone to contribute this (and also plötzblog). I can help if needed.

**Comment by mlduff** [comment]
@vabene1111 Okay I'd be happy to take this on - would you be able to assign me to both issues please?
