### ISSUE TITLE
New Site: https://gshow.globo.com/receitas-gshow/

### ISSUE THREAD

**Issue by fboaventura** [hhursev/recipe-scrapers#109]
Site: https://gshow.globo.com/receitas-gshow/
Recipe: https://gshow.globo.com/receitas-gshow/receitas/strogonoff-de-frango-simples-4fbe8cc656ec5b3c9801b7e5.ghtml

**Comment by bluhmr** [comment]
I think this is handled in  PR #274  the link above reroutes to the website we scrape in globo.py
