### ISSUE TITLE
New Site: https://mdemulher.abril.com.br/receitas/

### ISSUE THREAD

**Issue by fboaventura** [hhursev/recipe-scrapers#110]
Site: https://mdemulher.abril.com.br/receitas/
Recipe: https://mdemulher.abril.com.br/receitas/estrogonofe-de-carne/

**Comment by sloanemk** [comment]
This is handled in PR #274, link above reroutes to the website we scrape in abril.py

**Comment by bfcarpio** [comment]
Closed by #274
