### ISSUE TITLE
New website scraper request, hellofresh.se

### ISSUE THREAD

**Issue by patrikdolsson** [hhursev/recipe-scrapers#1136]
Please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login), and add sample recipe URL(s) below:

- https://www.hellofresh.se/recipes/vietnamesisk-notfars-64143ec27bee82308d551397
- https://www.hellofresh.se/recipes/vietnamesisk-notfars-65d898b3af98375703347268

**Comment by mlduff** [comment]
@jayaddison I'd be happy to implement this if you want to assign me.

**Comment by jknndy** [comment]
@mlduff , I believe coverage for this site is already included. I was able to scrape successfully and additionally it's listed in your README changes in #1105

**Comment by patrikdolsson** [comment]
That's so strange... It does seem to work on my end now as well

**Comment by jknndy** [comment]
No worries, we always appreciate a bug report! 

Closing this issue now.
