### ISSUE TITLE
Gousto.co.uk not parsing some ingredients correctly

### ISSUE THREAD

**Issue by ThomasHFWright** [hhursev/recipe-scrapers#1156]
**Pre-filing checks**

- [X] I have searched for open issues that report the same problem
- [X] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://www.gousto.co.uk/cookbook/chicken-recipes/sticky-orange-chicken

...

For ingredients such as `'1 320g British skinless chicken thighs'` I'd expect this to come through as just `'320g British skinless chicken thighs'`
With `'1 1 tbsp cornflour'` I'd expect this to come back as `'1 tbsp cornflour'`

Bit more complex, for '2 80g mangetout' I'd expect this to come back as "160g mangetout" if possible

...

With 14.56.0, scraper.ingredients() come back as:
`['15ml rice vinegar sachet', '1 1 orange', '1 1 tbsp cornflour', '15g fresh root ginger', '20ml toasted sesame oil', '1 320g British skinless chicken thighs', '2 80g mangetout', '2 1 spring onion', '1 Brown rice', '2 1 garlic clove', '24ml soy sauce']`

...

This is affecting importing recipes into Tandoor https://github.com/TandoorRecipes/recipes/issues/3194

**Comment by jayaddison** [comment]
Hi @ThomasHFWright - thanks for the bugreport - sorry it's taken a while to respond!  I'm planning to investigate this problem soon, likely within the next few days.

**Comment by jayaddison** [comment]
...apologies; I didn't get around to that, but should have time to soon (again, next few days).

**Comment by jayaddison** [comment]
@ThomasHFWright can you provide any other example URLs where this problem occurs?

**Comment by jayaddison** [comment]
I'm going to close this, because opening the recipe in a web browser displays the text "1 1 tbsp cornflour", along with the other unusually-described ingredient quantities.  So I think this indicates that we're retrieving the results as displayed, but that there could be a data issue on the recipe website itself.
