### ISSUE TITLE
shopping list is not visible

### ISSUE THREAD

**Issue by oekomat** [hhursev/recipe-scrapers#1164]
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https:// ...

...

**The results you expect to see**

...

**The results (including any Python error messages) that you are seeing**

...

**Comment by jknndy** [comment]
@oekomat , I will be closing this issue as it does not provide any information related to your bug. Additionally, this library does not offer a shopping list feature.
