### ISSUE TITLE
Allrecipes

### ISSUE THREAD

**Issue by sttrebo** [hhursev/recipe-scrapers#1169]
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://www.allrecipes.com/recipe/24871/beef-samosas/

...

complete recipe import

...

only getting partial import.  instructions, image, and text fields look complete.  but scraper seems to fail after the first ingredient.  attached is the .json of the imported recipe.
[Beef Samosas.json](https://github.com/user-attachments/files/16131982/Beef.Samosas.json)

...

**Comment by jayaddison** [comment]
Hi @sttrebo - thank you for the bugreport!  This sounds similar to #1154 - could you check whether the problem still appears in version `14.57.1`, released recently?  It includes a fix that may resolve this.

**Comment by michael-genson** [comment]
That "1 cup flour" ingredient is Mealie's default when recipe scrapers fails to find any ingredients. It's not actually on the linked recipe. I'd bet it's the same issue linked above, which is now fixed

**Comment by sttrebo** [comment]
sorry for the late reply.  yes, 14.58.0 works good for me.
