### ISSUE TITLE
Whatsgabycooking.com no longer working for some recipies

### ISSUE THREAD

**Issue by Kipmo** [hhursev/recipe-scrapers#1170]
**Pre-filing checks**

- [X] I have searched for open issues that report the same problem
- [X] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://whatsgabycooking.com/chicken-larb-bowls
- https://whatsgabycooking.com/chicken-parmesan-meatballs
- https://whatsgabycooking.com/chicken-fajita-bowls/
- these are just a few examples
...

**The results you expect to see**

Properly scraped data
...

**The results (including any Python error messages) that you are seeing**

"recipe_scrapers was unable to scrape this URL"
...

**Comment by jayaddison** [comment]
I've merged a fix for this, and would expect that to be published in a release of `recipe-scrapers` within the next week or two.

**Comment by Kipmo** [comment]
Thank you!!
