### ISSUE TITLE
Americastestkitchen.com family missing now

### ISSUE THREAD

**Issue by Coryrichter94** [hhursev/recipe-scrapers#1172]
https://www.americastestkitchen.com/recipes/3181-roast-beef-tenderloin-with-caramelized-onion-and-mushroom-stuffing

I searched issues on github and it appears it used to be included but is no longer included.

**Comment by jayaddison** [comment]
Hi @Coryrichter94 - thanks for the bugreport.  Please could you add some more details about what you expect to happen, and the results you're seeing - including any error messages?  The version of `recipe-scrapers` that you're using could be helpful too.

**Comment by smilerz** [comment]
ATK is included in the 15RC

**Comment by jayaddison** [comment]
I'm relatively confident that upgrading to v15.0.0 should resolve this problem - but if not, let us know and we can reopen the bugreport.
