### ISSUE TITLE
Clarify introductory steps in the README file (opening a Python session, expected interpreter output, ...)

### ISSUE THREAD

**Issue by jonzey231** [hhursev/recipe-scrapers#1180]
This is definitely a "me" problem but I just don't know how to run this script. I'm trying to use it to scrape all the different recipe URLs from HelloFresh, and probably a couple other websites as well.

I've spent a few hours trying to figure it out now. To be frank, it isn't just this one, I just don't know how to run them.

**Comment by jayaddison** [comment]
Thanks for the bugreport @jonzey231.  What happened when you tried to run the script, and how did that differ from what you expected?

**Comment by jonzey231** [comment]
I don't know how to run it in the first place. I guess I'm asking for help on how to actually use this.

**Comment by jayaddison** [comment]
Ok, no problem - to confirm, you do have Python and `pip` installed, yep?

**Comment by jonzey231** [comment]
Correct. Both are installed in Windows.

**Comment by jayaddison** [comment]
Ok, great!  Next up is to check whether you've been able to get this library (`recipe-scrapers`) installed -- and then let's figure out the first recipe for you to scrape.  Have you begun reading the `README` file or should I give you some time to review that first?

**Comment by jonzey231** [comment]
Awesome. I have it installed!

**Comment by jonzey231** [comment]
I'm just getting `scraper: command not found`

**Comment by jayaddison** [comment]
Hrm, OK.  Could you try running `python` before entering the next commands?  Here's more-or-less the output you should get (the text on the first line will probably be different on your system):

```pyi
> python
Python 3.12.4 (main, Jun 12 2024, 19:06:53) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from recipe_scrapers import scrape_me
>>> 
```

**Comment by jonzey231** [comment]
This is my output when I run `python`

```
>python
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

This is my output when I run `python  from recipe_scrapers import scrape_me`

```
File "<stdin>", line 1
    python  from recipe_scrapers import scrape_me
            ^
SyntaxError: invalid syntax
```

**Comment by jonzey231** [comment]
Maybe I'm just not sure what command to actually run at this point?

**Comment by jonzey231** [comment]
Update: I misunderstood what you meant.

When I run `python from recipe_scrapers import scrape_me` this is the output:

```
\Desktop\recipe-scrapers-main>python from recipe_scrapers import scrape_me
python: can't open file 'C:\Users\jonze\OneDrive\Desktop\recipe-scrapers-main\from': [Errno 2] No such file or directory
```

**Comment by jayaddison** [comment]
That's OK, take your time.  Could you try them as two separate commands?

1. `python` - to open a Python interpreter session (the `>>>` should appear as a prompt).
2. `from recipe_scrapers import scrape_me` - this is a statement within the Python session; we're asking it to import a function named `scrape_me` from this library.

**Comment by jonzey231** [comment]
Got it. Now I'm here:

```
Desktop\recipe-scrapers-main> python
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from recipe_scrapers import scrape_me
>>>
```

**Comment by jayaddison** [comment]
Excellent :)  OK.  Do you have any particular recipe webpage that you want to scrape from, or should we choose one at random?

**Comment by jonzey231** [comment]
So my original hope was to just get all HelloFresh recipe URLs but it seems like that isn't going to be possible.

Let's use this one: https://www.hellofresh.com/recipes/vegan-firecracker-mushroom-rice-bowls-666863a6223895220f198073

**Comment by jayaddison** [comment]
Afraid not, yep - it's one URL at a time.  We can use that one though, to get a sense for how the functionality works.  That would be:

```pyi
scraper = scrape_me('https://www.hellofresh.com/recipes/vegan-firecracker-mushroom-rice-bowls-666863a6223895220f198073')
```

**Comment by jonzey231** [comment]
Done!

**Comment by jayaddison** [comment]
Ok, we've got ourselves a `scraper` variable :)  Now you should be able to use that to access the information from the recipe -- also, it's boring, but I should mention: please be responsible if re-publishing information from recipes (the core of recipes are not copyrightable in many places, but some aspects of the site's content may be).

```pyi
>>> print(scraper.title())
>>> print(scraper.ingredients())
```

**Comment by jayaddison** [comment]
If it's OK with you: I'll edit the title of this thread because the discussion gives me a few ideas for how we can improve the top of our `README` file (so thank you!).  If you'd prefer though, I can omit any references to this conversation when making those changes (and I'll leave the thread title as-is).

**Comment by jayaddison** [comment]
You're welcome - you too!
