### ISSUE TITLE
Bypass Cloudflare script

### ISSUE THREAD

**Issue by vdbrink** [hhursev/recipe-scrapers#1195]
I was investigating to add the domain www.boodschappen.nl to the recipe scraper.
I found out the website contains the required scheme and based on the html I can extract the required data via a new created test file.

The only problem, while running the `scrape_me()` python script, is that there is a (Cloudflare) javascript before the real website is loaded. 
One possible workaround could be to load and run the javascript, that requires a real load in a browser.
The other solution is maybe to extract the redirect url, with some regular expression, and then redirect it.

Is it possible and desirable to add such a way to bypass this proxy/bot detection to the scraper? To also support this recipes website or do you only support direct accessible websites?

Example urls for this domain are: 
* https://www.boodschappen.nl/recept/kardemomkoekjes-met-pistache/
* https://www.boodschappen.nl/recept/pastasalade-met-gerookte-kip-tomaatjes-en-honing-mosterddressing/

They have a lot recipies that I want to scrape!

**Comment by vdbrink** [comment]
I found this blog with multiple ways to bypass this https://www.zenrows.com/blog/bypass-cloudflare

**Comment by jayaddison** [comment]
Hi @vdbrink - sorry, this doesn't seem like the kind of functionality that we want to support; I agree that mechanisms like this can make it difficult to retrieve information, but how to configure those is the choice of the website owners, and we won't circumvent that.

**Comment by vdbrink** [comment]
Hi @jayaddison, I totally understand that this is not functionality for the default scraper.
Maybe when there are more sites like this it's maybe profitable to support this (with the use of another script which handles it).
