### ISSUE TITLE
Add Velogosi

### ISSUE THREAD

**Issue by airon90** [hhursev/recipe-scrapers#125]
Link: https://www.vegolosi.it/
Recipe: https://www.vegolosi.it/ricette-vegane/fagottini-di-zucchine-ripieni-di-seitan/

You can find in the source code all structure data in json format

**Comment by tobiaghiraldini** [comment]
I already built this scraper, and I'll take some time to make a pull request in the very near future (this evening or tomorrow at last).

**Comment by tobiaghiraldini** [comment]
@hhursev please close the issue referencing the merged pull request ;)

**Comment by hhursev** [comment]
Closed in #152
