### ISSUE TITLE
Add Cucchiaio.it

### ISSUE THREAD

**Issue by airon90** [hhursev/recipe-scrapers#126]
Link: https://www.cucchiaio.it/
Recipe: https://www.cucchiaio.it/ricetta/ricetta-risotto-zucca-birra-liquirizia/

You can find in the source code all structure data in json format

**Comment by tobiaghiraldini** [comment]
I'm almost finished with this scraper, and I'll take some time to make a pull request in the very near future (this evening or tomorrow at last).

**Comment by tobiaghiraldini** [comment]
Sorry for the delay.. I just created a pull request with the cucchiaio.it scraper.
