### ISSUE TITLE
Note: off-branch git tag for release 15.2.0

### ISSUE THREAD

**Issue by jayaddison** [hhursev/recipe-scrapers#1272]
During preparation of the [15.2.0 release](https://github.com/hhursev/recipe-scrapers/releases/tag/15.2.0), I'd forgotten to pull the latest changes from `main` before creating the [`15.2.0` tag](https://github.com/hhursev/recipe-scrapers/tree/15.2.0) (at 0a5c19e2159af88a8e8cbaa59a96a40692d0befb) in git.  Typical!

I rebased `main`, but forgot to update that tag before initiating the release process.  @hhursev any chance you could yank the 15.2.0 release from PyPi?

(in this case it shouldn't contain any differences from the intended release commit (19eb5fcafdea9404b9e76c79f8f589ee8e2ee788), because the only missing commit was test-related-only.. but even so, in principle it's best for the releases to be accurate, and to have corresponding tags on the expected branch...)

**Comment by jayaddison** [comment]
@hhursev any chance you could help with this?

In short: I'd like to yank the 15.2.0 release because it was released from an off-branch commit.

I should probably try to add a check to the workflow so that this doesn't happen again, too.

**Comment by jayaddison** [comment]
> I should probably try to add a check to the workflow so that this doesn't happen again, too.

This would also need to handle the case of releases from the `v14` branch (currently releases should occur either from `main` or `v14`, but not elsewhere).

**Comment by hhursev** [comment]
yanked out from PyPi

**Comment by jayaddison** [comment]
Thank you!
