### ISSUE TITLE
License information for test data

### ISSUE THREAD

**Issue by bkmgit** [hhursev/recipe-scrapers#1348]
Would be helpful to add licensing information for the test data:
https://github.com/hhursev/recipe-scrapers/tree/main/tests/test_data

**Comment by jayaddison** [comment]
Thank you @bkmgit, this is a good idea.  Those files are obtained from the public web, and are copyright to their respective authors/publishers.  Neither they nor the test suite are included in releases of `recipe-scrapers` -- even so, we should add some documentation about this within the source tree.

**Comment by jayaddison** [comment]
Some documentation for this is now in progress in pull request #1349.

**Comment by jayaddison** [comment]
Ok, I've had some more time to consider and adjust some possible licensing documentation.  @bkmgit Could you let me know whether the text in #1349 would provide the information you're looking for, and/or any suggestions for concerns that it does not cover?

**Comment by hhursev** [comment]
Why is this a good idea @jayaddison? Can you elaborate more?

**Comment by jayaddison** [comment]
Sure, I'll try.  I think there are two audiences for it:

* Developers: early in my contributing here, at some point I got a bit worried that the PyPi packages might contain the test HTML, and that some recipe site owners might reasonably want their content removed from those in future.  After reading the `MANIFEST.in` (now translated to `pyproject.toml`), I reassured myself that no, those files are excluded.  I think that it could be useful to document that for future developers.

* Content owners: yes their recipe sites are public, and we're only retrieving a minimal number of test HTML files for quality/review/test purposes.  We know that, but I feel that on initial inspection someone might worry that we're copying their content.  I'd like to reassure them as much as possible about the reasons for a selection of one or two test files -- but also not to assume that they'll agree, hence also explaining removal options at the same time.

**Comment by hhursev** [comment]
When you say “I got a bit worried … some recipe site owners might reasonably want their content removed” how confident are you that you understand what part of a recipe is copyrightable and if we violate something here to begin with?

**Comment by jayaddison** [comment]
It's a good question - I think I'd refer to https://github.com/hhursev/recipe-scrapers/issues/1012#issuecomment-2198196651 where I describe some concerns and my level of understanding of recipe copyright.  In particular:

> To a certain extent, food recipes -- lists of ingredients and a description of how to prepare them -- especially those that do not include any unpublished trade secrets -- are generally not protectable using copyright law in the legal systems I'm aware of.
>
> However, some web recipe authors do earn income from their websites, and so they have a reason to want to protect their recipes, and could reasonably be concerned about code that can provide access to them.
>
> Advice can be found on the web about ways to create recipes that make them more likely to be copyrightable - some of this explains, for example, that photography and imagery is copyrightable, and some of it explains that it is possible to add distinct written elements in or around the core of the recipe to improve the chance that legal proceedings would consider it copyrightable.
>
> In addition, there is historical precedent that although a typical individual recipe may not be copyrightable, cookbooks -- that is, multiple recipes that have been collected, curated and published together -- can be.

**Comment by jayaddison** [comment]
Thank you, @hhursev!
