### ISSUE TITLE
[DEV-Question]: Problem with test test_readme

### ISSUE THREAD

**Issue by ReneNulschDE** [hhursev/recipe-scrapers#1351]
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

First of all: I'm new in the club and thanks for this great componenent. 

I have added a new scraper aldinord, and added the urls and readme settings.

Now I'm struggling with test_readme test.

Whenever I add only one additional domain the test runs fine.

command: `python -m unittest -k test_readme`

readme:
```
- `https://aldi-nord.de/ <https://aldi-nord.de/>`_
    - `.es <https://aldi.es/>`_
```
init:
```
    AldiNord.host(): AldiNord,
    AldiNord.host(domain="aldi.es"): AldiNord,
```
Test output:
```
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK

```

Whenever I add more then one domain it fails:
readme:
```
- `https://aldi-nord.de/ <https://aldi-nord.de/>`_
    - `.es <https://aldi.es/>`_
    - `.lu <https://aldi.lu/>`_
```
__init__.py:
```
    AldiNord.host(): AldiNord,
    AldiNord.host(domain="aldi.es"): AldiNord,
    AldiNord.host(domain="aldi.lu"): AldiNord,
```
Test output
```
F
======================================================================
FAIL: test_includes (tests.library.test_readme.TestReadme.test_includes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rene/projects/recipe-scrapers/tests/library/test_readme.py", line 175, in test_includes
    self.fail(
AssertionError: Missing top level domain(s) for primary domain aldi-nord.de

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
```

Any help would be great. The relevant code is available here:
https://github.com/ReneNulschDE/recipe-scrapers/tree/feat--New-scraper-Aldi-Nord

Thx
PS: I tried to understand a lot of comments in PR #1105 but here we are...

PSS:
All the Aldi stores worldwide are splitted between the two sons (Aldi Nord and Aldi Sued). I'm trying to implement a new scraper for all the websites of the "Aldi Nord" group (and in 2nd PR later "Aldi Sued") (There is already an aldi implementation but for Australia only, and they use a older version of the webstack)

The Nord-group has multiple websites with the same structure:
aldi-nord.de (In Germany they splitted the market too)
aldi.es
aldi.lu ... and some other

**Comment by jayaddison** [comment]
Thanks for the bugreport @ReneNulschDE!  I think this may be a side-effect of a change I made in #1162.

In short: one of the library tests began failing in a downstream distro test environment, where the `README.md` file was not found when the `test_readme` test runs (#1160).

What might fix/workaround it locally: try `pip install -e .` from the base `recipe-scrapers.git` directory.  That'll (re)install the package metadata, and hopefully that'll allow the test to read the updated recipe site list.

This has been on my mind as a limitation/problem for a while, but I don't yet have suggestions for how to improve it.

**Comment by ReneNulschDE** [comment]
Thanks for the fast feedback. I rerun this after after each change to the readme.rst already to make sure that `recipe_scrapers.egg-info/PKG-INFO` gets updated.

**Comment by jayaddison** [comment]
Ok - hmm, there must be something else going on here then.  I'll take a look at the code soon, thanks for providing that.

**Comment by ReneNulschDE** [comment]
Thanks, my the problem is that the root package is aldi-nord.de but the subpackages are aldi.es, aldi.nl, aldi.lu and so on...

**Comment by jayaddison** [comment]
That's certainly possible, yep!  Although I understand that you want to group them by business unit, does the test pass if you arrange them based on top-level domain name in the README?  (so, I think that would be three separate entries):

```
- `https://aldi-nord.de/ <https://aldi-nord.de/>`_
- `https://aldi.es <https://aldi.es/>`_
- `https://aldi.lu <https://aldi.lu/>`_
```

**Comment by jayaddison** [comment]
It's some kind of bug/problem related to `parse_secondary_line` I think.. I haven't quite narrowed in on it yet.

**Comment by jayaddison** [comment]
Hmm.. alternatively, I wonder if using separate classnames for each of the top-level domains would help here (`AldiES`, `AldiLU`, ...).  They could inherit from the same base class (`AldiNord`; `class AldiES(AldiNord)`).

Designing for a specific (and somewhat complicated) test case doesn't seem ideal - unfortunately I've lost much of the context about how it works (and it's going to take me a while to regain that).

**Comment by ReneNulschDE** [comment]
Whenever this ok yor you, I can create subclasses - Let me check it and potential conflicts with the old aldi scraper. I'll come back here or with a PR :-)

**Comment by ReneNulschDE** [comment]
@mlduff : looks like you created the test case, let me know if you have more insights. I will try the base class way for now.

**Comment by jayaddison** [comment]
@ReneNulschDE one more idea: does placing the subdomains into a comma-separated list on a single line resolve the problem?

(compare with `hellofresh` subdomains)

**Comment by ReneNulschDE** [comment]
@jayaddison : YEAH, this solves this. Thank you - like your responsiveness! PR is in the making.

**Comment by jayaddison** [comment]
You're welcome.  If/when you have time after that pull request, I'd be very glad for a separate bugreport saying something like "when multiple subdomains exist, the error message from test_readme can be misleading".  (let's make it easier for other people to write their readme entries correctly)
