### ISSUE TITLE
Preparation for v15.3.0

### ISSUE THREAD

**Issue by jayaddison** [hhursev/recipe-scrapers#1374]
Here's what I've prepared so far as a commit message for an upcoming v15.3.0 release.  Generally I tend to add all the pull request numbers when creating the corresponding [release](https://github.com/hhursev/recipe-scrapers/releases) on GitHub (from the git tag.. and causing the [GitHub Actions `publish` workflow](https://github.com/hhursev/recipe-scrapers/blob/12486a0125c9eec094f1deb36a3f32a0304f6fc4/.github/workflows/publish.yaml) to initiate).

----

Bump version to 15.3.0:

Adds support for:
- abeautifulmess.com
- aldi-nord (multiple)
- aldi-sued (multiple)
- barefootinthepines.com
- betterfoodguru.com
- beyondfrosting.com
- bitsofcarey.com
- brokenovenbaking.com
- cakemehometonight.com
- cambreabakes.com
- colleenchristensennutrition.com
- cookiesandcups.com
- cookomix.com
- cookwell.com
- hungryhappens.net
- kitchendivas.com
- krollskorner.com
- quitoque.fr
- rewe.de
- spainonafork.com
- thefoodietakesflight.com

Extends fields supported by:
- reciperunner
- recipetineats
- sallysblog
- saltpepperskillet
- simplycookit
- simplyquinoa
- skinnytaste
- spendwithpennies
- staysnatched
- sundpaabudget
- sunset
- sweetpeasandsaffron
- tastesoflizzyt
- tasty 
- thehappyfoodie
- thekitchenmagpie
- thekitchn
- therecipecritic
- thevintagemixer
- thewoksoflife
- themodernproper
- thinlicious
- timesofindia
- tineno
- tudogostoso
- usapears
- vegrecipesofindia
- wellplated
- womensweekly
- zenbelly

Bugfixes:
- maangchi: ingredient header regex fixup
- mccormick: filter-out redundant step-number instructions
- modernproper, usapears: filter redundant nutrient names from value output
- thekitchn: fixup for site name output
- timesofindia: search for ingredients only within ingredient-data container
- usapears: fixups for ratings/author retrieval
- _utils: reject empty input to 'get_yields' function
- _schemaorg: don't return zero servings for empty-string recipeYield

Removals:
- sundpaabudget: removal nutritional information
- thexpertguides: remove scraper

Misc:
- python: declare Python3.13 support
- test data: add LICENSE notice
- ci: upgrade to Ubuntu 24.04 for most GitHub Actions workflows
- ci: upgrade MacOS version for unittest GitHub Actions workflow
- ci: enable 'pip' caching in unittest, linters GitHub Actions workflows
- ci: restore 'unittest-parallel' for unittest GitHub Actions workflow
- ci: suppress noisy static-value exception messaging during unittest GitHub Actions workflow
- ci: remove dependency on 'tox' from GitHub Actions unittest and linters worklows
- tests: improve robustness of DeprecationWarning test cases
- project: update authorship and copyright details
- release: GitHub Actions: confirm release commit is found on release branch

----

In this case there are more items in the release note than usual, so it could take a while to annotate them with the pull request (especially because there's not a 1-1 mapping).  Even so, I find it a useful process to do during a release - it helps as a reminder about what's included, and allows for some re-inspection of the details.

Edit: update added-support list (x4)
Edit: update extended-field-support list (x2)

**Comment by jayaddison** [comment]
Contributors for this release are: @hhursev @jayaddison @jknndy @oahnh @romainchassaigne ... am I omitting anyone?

I'd also like the following items to be merged before release:

 - #1368 
 - #1373 
 - #1320 
 - #1367
 - #1370
 - #1371

**Comment by jayaddison** [comment]
> * [Tests: limit description text comparison length, to reduce risk of infringing copyright #1373](https://github.com/hhursev/recipe-scrapers/pull/1373)

Update: we'll exclude this from the upcoming v15.3.0 release.

> * [Fix additional details extraction in ATK scraper #1320](https://github.com/hhursev/recipe-scrapers/pull/1320)

I'm not yet certain about this one, given that we are not including #1373 - so I'm planning to defer it until a later time.

**Comment by jayaddison** [comment]
I'm still not sure about #1320, so I'm going to take some time to pause (for likely a week or two) before preparing this release.  If anyone else would prefer to go ahead and manage/publish the release, that's of course fine.

**Comment by jayaddison** [comment]
> Arg. My changes in #1312 seem to have broken the release GitHub Actions workflow.

Ideally I'd like to reintroduce a check like that, since it was intended to prevent an issue like #1272 from happening again.  However: for this one release I'll instead revert #1312, bump the version number again, and be careful to release that from on-branch `main`.

**Comment by jayaddison** [comment]
v15.3.2 (with two small patches - 846d9e759c21eaa88ee95ba03df4114ac0a79f97, de6dc334934925b258b3e19d0b2a2f0b33f2812a) has been release to PyPI, as has v14.61.0 that contains a backport of the latest changes to the `v14` branch.  Thank you all!

**Comment by jayaddison** [comment]
@jknndy @hhursev I've been a bit stressed out personally recently and am planning to take a temporary break from dev/review/maintenance - perhaps until Jan next year.

I'm also independently seeking some legal guidance for RecipeRadar, and I'd like that to extend to covering `recipe-scrapers` to provide some reassurance (mainly reassurance for me on behalf of the company, but ideally I'd like the outcome to include reasonable guidance we could apply/include here).  I feel a bit conflicted about that and am not certain how the process will go -- in worst-cases I could imagine it introducing problems or reduce my ability to contribute, despite me thinking that we are on reasonably solid ground at the moment -- but wanted to mention it.

**Comment by jknndy** [comment]
> I've been a bit stressed out personally recently and am planning to take a temporary break from dev/review/maintenance - perhaps until Jan next year.

Understood! I appreciate all the reviews (& guidance) over the last few months. This is the perfect time of year for a break, I hope you have a wonderful holiday season & to see you back in the new year. Happy holidays!

**Comment by hhursev** [comment]
> I've been a bit stressed out personally recently and am planning to take a temporary break from dev/review/maintenance - perhaps until Jan next year.

Taking breaks is always good for personal wellbeing - enjoy the time off and the holidays!

> I'm also independently seeking some legal guidance for RecipeRadar, and I'd like that to extend to covering recipe-scrapers to provide some reassurance (mainly reassurance for me on behalf of the company, but ideally I'd like the outcome to include reasonable guidance we could apply/include here). I feel a bit conflicted about that and am not certain how the process will go -- in worst-cases I could imagine it introducing problems or reduce my ability to contribute, despite me thinking that we are on reasonably solid ground at the moment -- but wanted to mention it.

Regarding the legal guidance - recipe-scrapers is and will remain a simple MIT-licensed scraping tool. While I appreciate you keeping us informed, no changes to recipe-scrapers will be needed from this process, as the current approach and license serves its purpose perfectly.
