### ISSUE TITLE
can you add hellofresh.nl

### ISSUE THREAD

**Issue by Pherax** [hhursev/recipe-scrapers#138]
Hi can you add hellofresh.nl (domain add)

HelloFresh.host(domain='nl'): HelloFresh, to line 83 of __init__.py

**Comment by jayaddison** [comment]
What's your use case for this @Pherax?

It looks like HelloFresh recipes on any domain (i.e. 'nl') are also available on other domains (i.e. 'com').

Example:
- https://www.hellofresh.co.uk/recipes/thai-style-pork-stir-fry-5b642855ae08b557c72ac262
- https://www.hellofresh.com/recipes/thai-style-pork-stir-fry-5b642855ae08b557c72ac262

**Comment by jayaddison** [comment]
Hi @Pherax - I'm closing this issue for now, but please feel free to re-open it when you have more details to share from your use-case.
