### ISSUE TITLE
Add scraper for cookomix.com

### ISSUE THREAD

**Issue by Lucky-Strike1695** [hhursev/recipe-scrapers#1385]
Please add support for cookomix.com.
Wild mode works but breaks down every steps in unnecessary substeps.

Recipes example :
- https://www.cookomix.com/recettes/risotto-champignons-et-courgettes-thermomix/
- https://www.cookomix.com/recettes/brownies-thermomix/

Thanks !

**Comment by Lucky-Strike1695** [comment]
Thanks for your quick work.
It seems to be working good !

Only one (small) issue : Cookomix gives a preparation time and a total time, but Mealie takes the total time as the cooking time instead. 
It should take preparation time and total time from Cookomix and calculate cooking time from total - prep.

Anyway, thanks a lot !

**Comment by jknndy** [comment]
> Only one (small) issue : Cookomix gives a preparation time and a total time, but Mealie takes the total time as the cooking time instead. It should take preparation time and total time from Cookomix and calculate cooking time from total - prep.

The scraper is returning separate returns for `prep_time`, `cook_time` and `total_time` so this would be a bug report for Mealie!

For example the test case in #1393 includes
```json
  "total_time": 51,
  "cook_time": 41,
  "prep_time": 10,
```

**Comment by Lucky-Strike1695** [comment]
Hi,
A few years later, I found out that the scraper fails to retrieve the whole recipe if its divided in 2 or more parts.
For instance : https://www.cookomix.com/recettes/tarte-brocolis-roquefort-thermomix/
On this link, only the first part (pie crust) is retrieved.

**Comment by jknndy** [comment]
Hi @Lucky-Strike1695 , are you using the most recent version of the library? I'm not able to replacte the issue on my end. The site is returning the whole instructions list for me
<details>
  <summary>output</summary>
 
  ```json
    "instructions_list": [
        "La p\u00e2te bris\u00e9e",
        "Pr\u00e9chauffer le four \u00e0 180\u00b0C.",
        "Mettre 150 grammes de farine, 80 grammes de beurre demi-sel coup\u00e9s en morceaux et 50 grammes d'eau dans le Thermomix. P\u00e9trir 30 sec/mode p\u00e9trin.",
        "Transvaser le contenu du Thermomix dans un moule \u00e0 tarte chemis\u00e9 avec du papier cuisson.",
        "\u00c9taler la p\u00e2te dans le moule.",
        "La garniture",
        "Mettre 400 grammes de brocolis lav\u00e9s et coup\u00e9s en morceaux dans le Panier de cuisson.",
        "Mettre 500 grammes d'eau dans le Thermomix.",
        "Ajouter le panier de cuisson.",
        "Cuire 15 min/Varoma/vitesse 1 puis retirer le panier de cuisson.",
        "Ajouter les brocolis sur toute la surface de la p\u00e2te.",
        "Mettre 2 tranches de jambon cru fum\u00e9 coup\u00e9s en petits morceaux et (facultatif) en les parsemant sur les brocolis.",
        "Vider l'eau.",
        "Ajouter 2 oeufs, 200 grammes de cr\u00e8me fra\u00eeche \u00e9paisse dans le Thermomix.",
        "Mettre 150 grammes de roquefort coup\u00e9s en petits morceaux sur toute la surface de la p\u00e2te..",
        "Ajouter 1 pinc\u00e9e de sel, 1 pinc\u00e9e de poivre et 1 pinc\u00e9e de noix de muscade moulue dans le Thermomix. M\u00e9langer 15 sec/vitesse 5.",
        "Transvaser sur la pr\u00e9paration.",
        "Mettre 30 grammes de gruy\u00e8re rap\u00e9 sur la pr\u00e9paration.",
        "Mettre dans le four pendant 35 min \u00e0 180\u00b0C.",
        "Servir chaud ou  ti\u00e8de."
    ],
  ```
  
</details>
