### ISSUE TITLE
I built something using your library!

### ISSUE THREAD

**Issue by poundifdef** [hhursev/recipe-scrapers#139]
Hi! This isn't an issue, but I wanted to share something I built which uses your library to display a plain-text and printable version of recipes. Thank you for all of your hard work on this!

https://github.com/poundifdef/plainoldrecipe

I may add new scrapers to my own repo, and I follow a somewhat similar structure as you do. Feel free to copy them back into your code if you see anything that interests you.

**Comment by jayaddison** [comment]
Nice work @poundifdef!

Initially I think it may be difficult for `recipe-scrapers` to pull changes from your repository, since they are AGPL-licensed and `recipe-scrapers` is MIT-licensed.

That said, you're always welcome to open pull requests here.  Good luck with the project!
