### ISSUE TITLE
Support for 40aprons.com

### ISSUE THREAD

**Issue by jknndy** [hhursev/recipe-scrapers#1397]
Please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login), and add sample recipe URL(s) below:

- https://40aprons.com/easy-perfect-caramel-sauce/
- https://40aprons.com/creamy-grits/

**Comment by bencondemi** [comment]
I'd like to work on this!

**Comment by bencondemi** [comment]
Hi! Hoping to bump this. I would like to work on these for a school project and need to show evidence of communication with the project owners as one of the initial deliverables. Thanks!

**Comment by jknndy** [comment]
> Hi! Hoping to bump this. I would like to work on these for a school project and need to show evidence of communication with the project owners as one of the initial deliverables. Thanks!

Hi @bencondemi ,

Thanks for your interest in contributing to the project! I've assigned this issue to you (and will assign the others momentarily). Let me know if you run into any issues or have any questions about the dev process. We are always looking for input on how to improve the developer documentation!
