### ISSUE TITLE
Additional recipe sites

### ISSUE THREAD

**Issue by randycorley** [hhursev/recipe-scrapers#171]
Hi -

Thank you for maintaining this recipe-scraper which I intend to incorporate in a current project.  Following are a couple of excellent and extensive recipe sites that I frequently use:

foodandwine.com - Sample recipe:
https://www.foodandwine.com/recipes/balsamic-and-rosemary-marinated-florentine-steak

amazingribs.com - Sample recipe:
https://amazingribs.com/tested-recipes/pork-recipes/perfect-pulled-pork-recipe

It would be wonderful if these sites were added to your functionality.

**Comment by hotfix** [comment]
i will try to do it. the foodand wine is quite easy.

on amazinggrip html should be scaped.

what should be the total time in that case?

> Preparation time. It takes about 25 minutes to trim and rub the meat. 12 to 24 hours to let the salt penetrate.
> Cooking time. About 8 to 12 hours depending on a number of variables. See "Cooking time" below.
 should we calculate 25 min + 24h + 12h?

**Comment by randycorley** [comment]
Yes, that should be correct for total time.

However, I have a broader question as I’ve looking into this further.  I will be developing my app in iOS and your scraper is in Python.  Do you have any insights on how others have successfully integrated your scraper into an iOS application using Swift/SwiftUI?

Thanks,
Randy

Randall Corley | EVP, Global Compliance Officer
DJE Holdings, Inc. | 200 East Randolph Drive | Chicago, IL 60601 | U.S.A.
• Office: 312-552-1162 | Mobile: 312-371-9247
• randall.corley@djeholdings.com<mailto:randall.corley@djeholdings.com>

This message may contain information which is confidential and/or attorney-client privileged. If you are not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. Please advise the sender immediately by reply email and delete this message and any attachments without retaining a copy. Thank you.

For information on how Daniel J. Edelman Holdings, Inc. uses personal data and your rights, please see our Privacy Policy<https://www.edelman.com/privacy-policy>. Please reply to this email to notify us if you do not want us to contact you with information similar to the subject of this email communication.
