### ISSUE TITLE
Style preference, types, and formatting

### ISSUE THREAD

**Issue by bfcarpio** [hhursev/recipe-scrapers#187]
Hello,

I realize that i've been adding a bunch of parsers lately and I realized that I could also help out with repo maintenance so that you don't have to just bump versions every two days.

Is there an official style or format that the project intends to keep? I typically like to have an [editorconfig](https://editorconfig.org/) in my repo and use [black](https://github.com/psf/black) for Python.

Additionally, is there interest for using mypy to do static type analysis?

Just trying to feel the waters!

Thanks for this amazing repo!

**Comment by hhursev** [comment]
Hey!

You are more than welcome to help with the repo! Sent you an invitation.

Official format has so far been "personal PEP8 interpretation" 😄

However, you gave me some food for thought and I say let's add [black](https://github.com/psf/black) and [pre-commit](https://pre-commit.com/) to requirements.txt and run the check before commits! This will force python 3.6+ when developing - let's go for it.

If we have `black` set up I don't see much value in adding editorconfig so I wouldn't do that.

I'm personally against mypy due to the size and nature of this project. I also like to keep the project as simple as possible for newcomers. However, I'm open for ideas and comments.

Your help is appreciated! Makes me happy

**Comment by bfcarpio** [comment]
I'll agree with you that editorconfig is superseded by using `Black` and that maybe `mypy` isn't needed. 

This morning I read a handful of articles about using pre-commit so I can probably whip something up.

> This will force python 3.6+ when developing - let's go for it.

We'll have to make sure to remove the 3.6 testing in the CI/CD and list it as a minimum Python version. I'm not that familiar with Python packaging so I'll make sure to have you look that over.

Additionally, what are your thoughts to using a different way of specifying dependencies? When I was working on adding Parsers, it confused me that something like `coverage` was added as a production dependency when it's really a development one. `Black` would fall into a similar category here. As I mentioned before, I'm not the most familiar with Python's packaging, but wouldn't another project that imports `recipe-scrapers` also end up installing `coverage` needlessly with the way it's currently set up? The following links might describe some ways to doing this better if you're interested: 

+ https://pipenv.pypa.io/en/latest/

+ https://stackoverflow.com/a/28842733

**Comment by hhursev** [comment]
Hmm coverage should not have been installed as a production dependency! I'll look it up. Things like Black/pre-commit/flake8 should not be too.

The way it works when someone runs `pip install recipe-scrapers` is the content in the setup.py file at the root level is read. In there there is `install_requires` list and the dependencies there are the ones that get installed (and their dependencies and the dependencies of their dependencies and ... 🌳). Things from requirements.txt are ignored on `pip install recipe-scrapers` and intended for development use only.

Another file that is read and taken into account on pip install is the MANIFEST.in

**Comment by hhursev** [comment]
@bfcarpio running `pip install recipe-scrapers` in a fresh environment gave me the following dependencies:

```
soupsieve, beautifulsoup4, lxml, html-text, six, pyparsing, isodate, rdflib, rdflib-jsonld, w3lib, webencodings, html5lib, urllib3, idna, chardet, certifi, requests, mf2py, extruct, language-tags, requests-file, tldextract, recipe-scrapers
```

there is **no coverage** in the packages downloaded. Adding files in requirements.txt alone won't affect the production dependencies. I think what we currently have works just fine. (I'm strongly against pipenv too)

**Comment by bfcarpio** [comment]
Glad I was wrong!

Thank you for checking it out. I'll finish up #188 :smiley:
