### ISSUE TITLE
Bowlofdelicious Returning Not Implemented Error

### ISSUE THREAD

**Issue by alttutar** [hhursev/recipe-scrapers#189]

**Comment by bfcarpio** [comment]
I'll take a look into it! Thanks

**Comment by bfcarpio** [comment]
Could you confirm what version of the package you are using? I just tried with version 8.2.2 and it's working for the couple of recipes that I tried.

Could you also try importing it in a repl and doing a quick scrape that way?

**Comment by alttutar** [comment]
Upps, thanks for that! Just updated my version!
