### ISSUE TITLE
Thanks for the awesome work! Could you please add the following to sites to this list?

### ISSUE THREAD

**Issue by varsharc** [hhursev/recipe-scrapers#206]
Hi

Was wondering if you mind adding the the following two sites to this list:
1. Veg Recipes of India (https://www.vegrecipesofindia.com/)
2. Indian Healthy Recipes (https://www.indianhealthyrecipes.com/)

Thanks again!

---

Edit for checklist:
- [x] https://www.vegrecipesofindia.com/
- [x] https://www.indianhealthyrecipes.com/

**Comment by bfcarpio** [comment]
Scrapers have been added. Closing.
