### ISSUE TITLE
Hello Fresh [yields] returns error

### ISSUE THREAD

**Issue by ammacdonald3** [hhursev/recipe-scrapers#226]
Thanks for filing a bug report with us!

If your request is about a website that is not supported, please open a 'new scraper' issue request instead.

To help get the issue fixed, please fill in the information below.

**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://www.hellofresh.com/recipes/pork-flautas-supreme-5ec3de1d81d3ba5450034ddc

**The version of Python you're using**

... 3.7.3

**The operating system of your environment**

... Mac OS

**The results you expect to see**

... '2' or '4' (not sure which approach you're taking, as the source recipe site allows users to toggle between multiple sizes)

**The results (including any Python error messages) that you are seeing**

... INFO:root:exception_handling silencing exception: list index out of range

Can you write Python and would you like to help fix the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [ ] I'd like to try fixing this scraper myself
- [x] I'd like guidance to help me develop a fix
- [ ] I'd prefer if the `recipe-scrapers` team try to fix this

**Comment by bfcarpio** [comment]
Thank you for filing this bug, Andrew! Sorry if it caused any issues. 

I just did a quick check and it looks like this website implements the a JSON schema and it uses the data for 2 servings.

However, our parser doesn't use the JSON schema to get the data :disappointed: 

What are your thoughts on a fix for this?

**Comment by ammacdonald3** [comment]
Thanks so much for the quick reply, Brendan! I was able to retrieve the correct value by modifying the **yields** function in **hellofresh.py**, as shown below. I've never done a pull request before, but I'd definitely like to try. Does the code below look acceptable to you?

`def yields(self):
        return get_yields(
            self.soup.find(
                "span",
                {"data-translation-id": "recipe-detail.recipe-detail.serving-amount"},
            ).parent.parent.find("div", {"variant" : "secondary"}).contents[0]
        )`

**Comment by bfcarpio** [comment]
Can you make a PR with that code change? It'll be easier to read and comment on it from there.

I'm assuming that you already have a cloned version of the repo. Did you fork the repo or just clone this one?

You can roughly follow the example shown in [this article](http://www.dasblinkenlichten.com/how-to-create-a-github-pull-request-pr/). Essentially you want to create a new branch, commit your changes, and push your branch. Then, on Github you should see an alert that you can merge your branch. Fill out the information and we can proceed from there.
