### ISSUE TITLE
Broken Scraper -- acouplecooks.com

### ISSUE THREAD

**Issue by afichtenholtz** [hhursev/recipe-scrapers#231]
Thanks for filing a bug report with us!

If your request is about a website that is not supported, please open a 'new scraper' issue request instead.

To help get the issue fixed, please fill in the information below.

**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://www.acouplecooks.com/baked-eggplant-parmesan/

**The version of Python you're using**

v3.6.8

**The operating system of your environment**

CentOS Linux 7

**The results you expect to see**

Calls to scrape_me.ingredients() and scrape_me.instructions() should yield lists of strings

**The results (including any Python error messages) that you are seeing**

Python 3.6.8 (default, Apr  2 2020, 13:34:55) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from recipe_scrapers import scrape_me
>>> scraper = scrape_me('https://www.acouplecooks.com/baked-eggplant-parmesan/')
>>> scraper.title()
'Baked Eggplant Parmesan'
>>> scraper.total_time()
25
>>> scraper.yields()
'4 serving(s)'
>>> scraper.ingredients()
INFO:root:exception_handling silencing exception: 'NavigableString' object has no attribute 'text'
[]
>>> scraper.instructions()
INFO:root:exception_handling silencing exception: 'NavigableString' object has no attribute 'text'
''

Can you write Python and would you like to help fix the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [ ] I'd like to try fixing this scraper myself
- [x] I'd like guidance to help me develop a fix
- [ ] I'd prefer if the `recipe-scrapers` team try to fix this

**Comment by hhursev** [comment]
Instead of guidance you get an instant fix, sorry 😅 We don't need to use html parsing for the site anymore - thus switched to using schema. You can [check the commit](https://github.com/hhursev/recipe-scrapers/commit/d64f8b946ec988391b943c08e13b95e8f237d77a) if you are curious how this happened. Upgrade `recipe-scrapers` to 9.2.5
