### ISSUE TITLE
Rating total count?

### ISSUE THREAD

**Issue by osean-man** [hhursev/recipe-scrapers#254]
I can see in the allrecipe.py file you have a ratings method, however I don't see a total count of people who made up that rating. I'm assuming because it's really schema driven, those types of details are implementation specific. Is it alright if I make a change specific to that AllRecipes class to handle something outside the scope of the schema and specifically for allrecipes.com?

**Comment by sdiggles** [comment]
To be clear, the total amount of reviews. 
![reviews](https://user-images.githubusercontent.com/60236923/98196228-9d4db800-1ef1-11eb-81ee-8ddacc9bf521.png)

**Comment by sdiggles** [comment]
To be clear:
![Baked-Ziti-I-Recipe-Allrecipes](https://user-images.githubusercontent.com/60236923/98196318-cec68380-1ef1-11eb-9bb3-7f9fa9360b43.png)

**Comment by hhursev** [comment]
I can see how this is useful! It's most definitely all right to make an addition specific to the allrecipes scraper 🍺  I'd create `rating_details` method or something along these lines. It's also OK adding other extra things you might need
