### ISSUE TITLE
Turkish Recipes

### ISSUE THREAD

**Issue by yuceenterprises** [hhursev/recipe-scrapers#256]
Hello there. There is no recipe website that includes recipes in Turkish. www.yemek8.com is a recipe hub that includes recipes from all Turkish recipe websites. Would you be so kind to add this one? (example recipe: https://yemek8.com/tarifdetayi/kori-soslu-tavuklu-patates-toplari-HzMDw8Pz9O) ("Malzemeler" section is the desired content which means "ingredients")

**Comment by hhursev** [comment]
What is the difference between yemek8.com and yemek.com? I added yemek.com as that's where I get redirected to when I want to see the recipe's instructions. (the recipe you've given is on https://yemek.com/tarif/kori-soslu-tavuklu-patates-toplari/ with cooking instructions)
