### ISSUE TITLE
Support for proxies

### ISSUE THREAD

**Issue by afichtenholtz** [hhursev/recipe-scrapers#260]
Since you're already using the requests library to handle your get in AbstractScraper, does anybody object to me adding the proxies option to the constructor?

**Comment by bfcarpio** [comment]
That's probably something that should be added with a `kwarg` or other generic config structure, but I'll leave implementation up to you.

Go for it! We can work out any kinks with the PR. Just please make sure to include documentation for any features you add.

**Comment by hhursev** [comment]
I love the idea! Do add please

**Comment by bfcarpio** [comment]
closed by #261
