### ISSUE TITLE
Language scraping is non-deterministic & could be updated to modern standard.

### ISSUE THREAD

**Issue by bfcarpio** [hhursev/recipe-scrapers#264]
I discovered this bug when looking at the Travis builds for #263. The language scraping was working for the builds running Python 3.6 and 3.7, but not 3.8.

The website being used in #263 implements both the current standard of `<html lang="hu">` and the old depreciated standard of `<meta http-equiv="Content-Language" content="hu-hu" />`. Our base scraper supports scraping both of these options with equal preference, which is one discussion point. Note, the [linked reference](https://www.w3.org/International/questions/qa-http-and-lang#meta) does include some logic on what to do.

> HTML5 did, however, make a concession for backwards compatibility. If there is a meta element with http-equiv set to Content-Language in the markup, and if there is no language attribute on the html tag, and if the meta element has a value that is a single language tag, then a browser can (not must) use that information to guess at the default language of the text on the page. Having said that, this is only for backwards compatibility, and you really shouldn't use this approach any more. Simply use a language attribute on the html tag.

A second interesting thing is that the base scraper stores the language codes in sets, but then makes the notion of grabbing the "first candidate language". Sets, [in maths](https://en.wikipedia.org/wiki/Set_(mathematics)), don't have an order. The two passing tests seem to have gotten lucky with which language was returned (see my example below) . I also remember something about a recent Python version (3.7?) doing something about `dicts` being ordered in implementation which might influence `sets` as well.

Which brings us to the question of ensuring a deterministic language selection of which there are several ways that it could be done including, but not limited to the following:

1. Stop scraping the depreciated method of the language.
2. Continue scraping the depreciated method, but lower the priority
3. Maintain equal priority between language specification methods and use a list to grab the first one deterministically
4. ~~Randomly sort the language list and grab the first one (joke).~~

I personally am leaning to Option 1 simply because the reference doc linked in the base scraper's comments was last updated in 2011 and I consider 9 years to be sufficient time for a depreciation notice.

I intend to remedy this bug, but if it's not solved within 30 days of this posting the community at large is welcome to submitting their PRs.

---

```
recipe-scrapers ⑂fix-mindmegette-after-layout-change* $ python -m coverage run -m unittest tests/test_mindmegette.py 
....{'hu', 'hu-hu'}
....
----------------------------------------------------------------------
Ran 8 tests in 1.131s

OK
recipe-scrapers ⑂fix-mindmegette-after-layout-change* $ python -m coverage run -m unittest tests/test_mindmegette.py 
....{'hu', 'hu-hu'}
....
----------------------------------------------------------------------
Ran 8 tests in 1.090s

OK
recipe-scrapers ⑂fix-mindmegette-after-layout-change* $ python -m coverage run -m unittest tests/test_mindmegette.py 
....{'hu-hu', 'hu'}
F...
======================================================================
FAIL: test_language (tests.test_mindmegette.TestMindmegetteScraper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/Liason/Documents/CodeProj/recipe-scrapers/tests/test_mindmegette.py", line 15, in test_language
    self.assertEqual("hu", self.harvester_class.language())
AssertionError: 'hu' != 'hu-HU'
- hu
+ hu-HU


----------------------------------------------------------------------
Ran 8 tests in 1.094s
```

**Comment by jayaddison** [comment]
Nice investigation and debugging @bfcarpio! - yep, this behaviour is a non-intuitive; it was added in #144 which could provide some background conversational context.

Personally my sense is that a lot of the content on the web is very old indeed, and that it'd be nice to continue to support that content.  That comes from a philosophical place about not repeatedly attempting to (re)write new content when we already have prior material to use and learn from.

That leans me towards wanting to retain as many language-detection methods as possible, in the hope that `recipe-scrapers` should be able to produce accurate metadata for the widest set of web recipes, old and new.

What it doesn't do is provide a clear answer about whether the current detection algorithm is any good.  But regardless of that, relying on `set` ordering does seem wrong, so I've opened a pull request to address that, whether it's the way we choose to go forward or not.

**Comment by bfcarpio** [comment]
I was thinking that one method would just be to use an `if`-block and follow the guidance of the attached resource:

```python
if modern_way():
    use_it()
elif older_way() and single_element():
    use_it()
else:
    return None
```

I don't know of a reason that we'd care about the `meta` tag information if the `html` tag exists; thus, I don't think it makes sense to allocate storage for them.
