### ISSUE TITLE
FoodNetwork.com is pulling page controls as data

### ISSUE THREAD

**Issue by ddelamare** [hhursev/recipe-scrapers#266]
Thanks for filing a bug report with us!

If your request is about a website that is not supported, please open a 'new scraper' issue request instead.

To help get the issue fixed, please fill in the information below.

**Pre-filing checks**

- [X] I have searched for open issues that report the same problem
- [X] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://www.foodnetwork.com/recipes/ina-garten/perfect-roast-turkey-recipe4-1943576

**The version of Python you're using**

Python 3.8.2

**The operating system of your environment**

Windows 10

**The results you expect to see**
In the ingredients list I expect to see only ingredients. I also noticed that the scraper is using the DOM elements to get the data instead of the ld+JSON which is available

**The results (including any Python error messages) that you are seeing**

- Deselect All
- 1/4 pound (1 stick) unsalted butter
- 1 lemon, zested and juiced
- ...

Can you write Python and would you like to help fix the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [X] I'd like to try fixing this scraper myself
- [X] I'd like guidance to help me develop a fix
- [ ] I'd prefer if the `recipe-scrapers` team try to fix this

**Comment by bfcarpio** [comment]
If you'd like to switch this parser over to use the schema data instead that would be great!

**Comment by micahcochran** [comment]
It seem like PR #386 clear this up.

```python
In [1]: import recipe_scrapers                                                  

In [2]: r=recipe_scrapers.scrape_me("https://www.foodnetwork.com/recipes/ina-gar
   ...: ten/perfect-roast-turkey-recipe4-1943576")                              

In [3]: r.ingredients()                                                         
Out[3]: 
['1/4 pound (1 stick) unsalted butter',
 '1 lemon, zested and juiced',
 '1 teaspoon chopped fresh thyme leaves',
 '1 fresh turkey (10 to 12 pounds)',
 'Kosher salt',
 'Freshly ground black pepper',
 '1 large bunch fresh thyme',
 '1 whole lemon, halved',
 '1 Spanish onion, quartered',
 '1 head garlic, halved crosswise']
```
