### ISSUE TITLE
Question: should the SchemaOrg 'yields' method call utils.get_yields?

### ISSUE THREAD

**Issue by jayaddison** [hhursev/recipe-scrapers#278]
The [`utils.get_yields` function](https://github.com/hhursev/recipe-scrapers/blob/6b2b338c5679f3f9a4a51a3653eb07755cf9cbd1/recipe_scrapers/_utils.py#L43-L66) tries to figure out whether a recipe is talking about 'servings' (number of people fed by the recipe) or 'items' (number of edible things produced by the recipe).

That's neat functionality; should we also (re)use this in the [`SchemaOrg.yields`](https://github.com/hhursev/recipe-scrapers/blob/6b2b338c5679f3f9a4a51a3653eb07755cf9cbd1/recipe_scrapers/_schemaorg.py#L71-L83) method?

**Comment by hhursev** [comment]
we should yeah.. reusing is generally good idea. Not sure why it's not used in SchemaOrg already

**Comment by bfcarpio** [comment]
@jayaddison If you have an implementation idea, I say get a quick demo going and ship it. It looks like we'll be making some big changes and we might as well make 1 large breaking version than 3 breaking versions in a row.

**Comment by jayaddison** [comment]
Sounds good @bfcarpio.  Making an initial attempt at this today, and should hopefully have a pull request available soon.
