### ISSUE TITLE
Idea: provide a way to retrieve instructions as a list

### ISSUE THREAD

**Issue by jayaddison** [hhursev/recipe-scrapers#283]
Although determining when one recipe instruction ends and where the next one begins can be a challenge, it'd be useful to scrape instructions in a list format similar to ingredients.

To maintain backwards-compatibility this could be done by adding an `instructions_list` (or perhaps a better-named..) method on the abstract scraper.  A naive default implementation could simply call `instructions` and split the result of that by newline.

**Comment by bfcarpio** [comment]
Could we do something akin to a builder pattern and have the invocation be like this: `scraper.instructions().list()`.

Not sure if it's "Pythonic", but we could have `instructions()` return a child class of `string` and implement a `list()` function onto it.

**Comment by jayaddison** [comment]
Sub-classing `str` feels a little risky to me - I'm not exactly sure why, but returning string-like-objects that have other embedded/overridden behaviours in them to callers feels like it could cause problems or be challenging to maintain in future.

**Comment by hhursev** [comment]
I'd vote for new method. Let's say `instructions_steps`. I'd probably go like:

In [_abstract.py](https://github.com/hhursev/recipe-scrapers/blob/master/recipe_scrapers/_abstract.py):

``` python
@Decorators.instructions_steps_naive
def instructions_steps(self):
    raise NotImplementedError("This should be implemented.")
```

in [_decorators.py](https://github.com/hhursev/recipe-scrapers/blob/master/recipe_scrapers/_decorators.py):

``` python
@staticmethod
def instructions_steps_naive(decorated):    
    @functools.wraps(decorated)
    def instructions_steps_naive_wrapper(self, *args, **kwargs):
        instructions_str = self.instructions()
        return instructions_str.split('\n')
    return instructions_steps_naive_wrapper
```
 
and in [_exception_handling.py](https://github.com/hhursev/recipe-scrapers/blob/master/recipe_scrapers/_exception_handling.py) adding the new method in the ON_EXCEPTION_RETURN_VALUES dict.

**Comment by bfcarpio** [comment]
I quite like that. Still getting into the groove with these decorators, but definitely the type of macro I'd have used in another language.

**Comment by jayaddison** [comment]
That sounds good to me too :+1:

**Comment by bfcarpio** [comment]
Somewhat related to this, I almost think that we should make instructions_list the new primary accessor and depreciate returning a string.

Without type hints or docs, if I saw a function called `instructions` I would have thought it returned a list. Furthermore, some instructions might have a newline in a single step. Joining the lines together removes that context.

```
2. # Blah
3. Knead the dough until bouncy

Note: feel free to add extra flour as needed
4 # Blah
```
An instruction in the form of a paragraph can simply be a list with a length of 1 allowing only minor changes to client code.

```python
[ "My aunt used to tell me to knead the bread with this technique..."]
```
Instructions with groups can simply be nested lists. More discussion needed here on whether to do this or if there's a good way to identify groups

```python
[["For the soup", "Get the odds the ends of the vegetables"], ["For the topping", "Mix cream and eggs"]]
```

Finally, when I was working on #302 I implemented a completely lazy variant of `_extract_howto_instructions_text`. I have a hunch that the join is a bottleneck. When running the tests you can see some groups of tests finish nearly instantly and some handful tend to linger. I noticed that the handful of longer ones were the ones involved with the instructions. More testing needed here for proof.

**Comment by jayaddison** [comment]
Mostly agree - I do see a challenge regarding instructions-with-groups; usually the group has a title, and I think it'd be worth including that in the same datastructure as the instructions themselves (it's tricky and more likely for client implementations to include subtle errors if they have to cross-reference between two datastructures to extract the representation of the information).

**Comment by thomascaillier** [comment]
Hey there,
I forked this project before I saw this issue, as well I refactored as you can see. As a first step, I would ignore the instructions-with-group part.
The solution I considered is an `instructions_steps` method also in [_schemaorg.py](/recipes-scrapers/_schemaorg.py) :
``` python
def instructions_steps(self):
    instructions = self.data.get("recipeInstructions") or []

    if isinstance(instructions, list):
        instructions_gist = []
        for schema_instruction_item in instructions:
            instructions_gist += self._extract_howto_instructions_text(
                schema_instruction_item
            )

        return [
            normalize_string(instruction) for instruction in instructions_gist if instruction
        ]

    return instructions
```
What do you think about that ?

**Comment by bfcarpio** [comment]
I like the idea of moving stuff out into a helper class for the short term. Feel free to make a PR.

**Comment by MarcusWolschon** [comment]
Sample data for real world instructions that are already formated as a list with no guessing involved:
```
"recipeInstructions":[
   {"@type":"HowToStep","text":"this is step 0"},
   {"@type":"HowToStep","text":"this is step 1"},
   {"@type":"HowToStep","text":"this is step 2"}
   ]
   ```

**Comment by jayaddison** [comment]
I'm looking into this at the moment, and thinking about one of two approaches to begin with.

Either of these would involve changes to the abstract scraper ([here](https://github.com/hhursev/recipe-scrapers/blob/e866830358dae17647ad0a9743eb57b387799726/recipe_scrapers/_abstract.py#L136-L137)) and schema.org handler ([here](https://github.com/hhursev/recipe-scrapers/blob/e866830358dae17647ad0a9743eb57b387799726/recipe_scrapers/_schemaorg.py#L199-L213)).

- Option 1: Add an `instructions_list` method that calls `instructions` and splits the returned value
  - Pros
    - Simple
    - Few changes required in the code

- Option 2: Add an `instructions_list` method that implements native instructions-as-lists, and then modify the `instructions` method to call it and `join` the results
  - Pros
    - Instructions would become a first-class data item within the library (debuggable, printable, reformattable, sortable, etc as individual entities) - and that _might_ be helpful when implementing instruction groups
  - Cons
    - Users continuing to call `instructions` would perform redundant string-to-list-to-string conversions
    - More challenging implementation; changes required in schema.org handling and also across all non-schema scrapers

I think a quick-fix using option (1) probably makes the most sense, to fulfil the feature request without too much work.  That wouldn't rule out _additionally_ implementing option (2) at a later date as a refactor.

**Comment by jayaddison** [comment]
(I might also use this as an excuse to try learning Python's [`ast`](https://docs.python.org/3/library/ast.html) module - it'd provide a chance to, for example, automatically rewrite the unit tests to use `instructions_list` tests that are an exact copy of the `instructions` tests, but with the multi-line strings replaced by lists)

**Comment by jayaddison** [comment]
For future reference / anyone's curiosity: the `ast` package turns out to be fairly low-level; very powerful, no doubt, but a little tricky to use for small maintenance scripts.

[`redbaron`](https://github.com/PyCQA/redbaron/) makes things significantly easier.  Here's a script that migrates _almost_* all of the unit tests with `test_instructions` methods to assert against lists-of-instructions instead of multiline-string-instructions:

```python
from glob import glob

import black
from redbaron import RedBaron
from redbaron.nodes import (
    AtomtrailersNode,
    StringNode,
)


def is_string_node(node):
    return isinstance(node.value, StringNode)


def is_atomtrailers_node(node):
    return isinstance(node.value, AtomtrailersNode)


def test_sources():
    for test_filename in glob("tests/test_*.py"):
        yield test_filename, RedBaron(open(test_filename, "r").read())


for test_filename, test_source in test_sources():

    # Find the instructions test method
    test_method = test_source.find("DefNode", name="test_instructions")
    if test_method is None:
        continue

    # Find the assertion call within the test method ("self.assertEquals")
    test_assertion = test_method.find(AtomtrailersNode.__name__)
    _, _, assertion_args = test_assertion

    # Extract the 'expected' and 'actual' values from the assertion call
    try:
        expected_value = next(filter(is_string_node, assertion_args))
        actual_call = next(filter(is_atomtrailers_node, assertion_args))
    except:
        continue
    _, _, actual_call_method, _ = actual_call.value

    # Strip the quotation characters from the start and end of the expected value,
    # replace escaped newlines, and split into non-empty lines
    quote_character = expected_value.value.value[0]
    expected_value_replacement = [
        line
        for line in (
            expected_value.value.value.strip(quote_character)
            .replace("\\n", "\n")
            .splitlines()
        )
        if line
    ]

    # Rename the test method and actual call method
    test_method.name = "test_instructions_list"
    actual_call_method.value = "instructions_list"

    # Replace the multiline expected-value with a string representation of the list
    expected_value.replace(f"{expected_value_replacement}")

    # Apply 'black' code formatting to the modified source and write it back to file
    formatted_source = black.format_str(test_source.dumps(), mode=black.FileMode())
    with open(test_filename, "w") as f:
        f.write(formatted_source)
```

* Note: one or two tests migrations are skipped due to exceptions retrieving the `expected_value` - this can happen, for example, when it's represented in the AST by a series of string concatenation calls (`str.__add__`, I guess?) instead of as a `StringNode`

**Comment by jayaddison** [comment]
There's an implementation-in-progess in #577, and we're spending a bit of time to decide on the method name (that could seem like a small concern, but it'll also affect the library for potentially a long time, so it seems worthwhile to pause).

I'm considering (and cautiously supportive of) this comment by @bfcarpio while thinking about the naming:

> Somewhat related to this, I almost think that we should make instructions_list the new primary accessor and depreciate returning a string.

Some thoughts:

- There would be a usage symmetry if both `instructions` and `ingredients` return lists
- _Some_ recipe schemas already declare instructions as lists (q: how many of total?)
- _Some_ non-schema websites declare instructions within list-like HTML structures (q: again, how many of total?)
- It could make writing scrapers more of a challenge - it's more effort than "just emit a blob of text"

After adding a list-based implementation using `str.split`, I'd be willing to go a few steps further and put the effort in to do a bulk refactor to make all scrapers and the schema-org parsing natively extract and emit lists.  Would that actually be a good direction for the library to move in though?
