### ISSUE TITLE
Question: why are the recipe functione like title() etc not implemented as class attributes?

### ISSUE THREAD

**Issue by ericmuijs** [hhursev/recipe-scrapers#310]
I wonder this because it seems a more logical implementation.

**Comment by hhursev** [comment]
That's an interesting question. Can you elaborate more why you believe class attributes are the more logical implementation?

As for why I've decided to go with function/methods - the reasoning is that the information extraction is executed at the time of invocation. This and given the unpredictable nature of scraping makes handling exceptions and unexpected cases easier to handle.

**Comment by ericmuijs** [comment]
Thanks for the answer. Well I'm a beginner programmer and just wanted to know the reasoning behind it. Exception handling seems fair enough :D
