### ISSUE TITLE
Discussion: Default and Error return conventions

### ISSUE THREAD

**Issue by bfcarpio** [hhursev/recipe-scrapers#318]
Copying over comments from #317:

@bfcarpio 
> As a note. I somewhat disagree with the error silencing implementation. If there's an error I'd either expect an exception to be thrown or None instead of "", -1 etc. I'm a polyglot-programmer so I might be intermixing conventions. This could be explained better in docs as well as have code comments for contributors implementing custom scraper to maintain convention.

@jayaddison 
> Re: exception silencing: I tend to be in the same boat as you about 'raising errors by default', but it's also true that web scraping can be very unpredictable. Perhaps there is a difference between "the scraper did not find what it was looking for as instructed by the code" and "an error occurred while running the scraper code for this field" - maybe we could provide sensible defaults in the former case? And/or a way for the developer to know that a default was returned?

---

I'm going to play around more with what the behaviour is and comment here.

**Comment by hhursev** [comment]
Not sure if I understand this issue. Right now the default behavior is to silence the errors and log with level INFO and DEBUG that we did so. This behavior may be changed by passing `exception_handling=False` to the `scrape_me` function. That will give devs the ability to handle exceptions as they find fit.

You'd like to change the default behavior to raising that exception, rather than logging it and the scraper to continue its work?

**Comment by bfcarpio** [comment]
There are two points. First is raising exceptions and second are the default values returned.

1. I think silencing exceptions should be opt-in. Since there are no doc strings that will pop up users may not know of this keyword argument. When consuming a new package that I just found I'd expect errors to be thrown. 
2. The default return values specified in the meta class aren't what I would consider ergonomic. I'm thinking specifically of string or collection returning functions like `title()` and `ingredients()`. I can see the following scenarios:
+ "" is returned because the website didn't specify a title. Scraper worked correctly. Not our fault and quite stupid, but I'd still have to check this.
+ "" is returned because someone didn't override the scraper and a default value was returned. Incorrect code worked correctly. Our fault and this should be addressed.
+ "" is returned because an error occurred and was silenced. Default value returned.
+ "" is returned because the scraper grabbed the wrong thing from the webpage. No errors thrown on the scraper, but maybe the website updated. Incorrect code working correctly.

Essentially a valid scrape could return the same thing as an invalid scrape. I'd think that returning `None` would be a better indicator that something didn't go as planned assuming an exception wasn't fired.

**Comment by hhursev** [comment]
I agree with everything! That would be a major version release.

On:

1) I'm with mixed feelings. I see pros and cons in what you propose and I'm becoming more aligned with you the more I think. So let's go ahead and make the change.

I always imagined people consume the package by writing mechanism to crawl recipe sources, scrape and save in db. After that data normalization starts. So I'd expect most package consumers not to want to bother with exception handling.

How about we do the following:

- Raise errors by default. Add **text in the exception message** that instructs how the exceptions can be silenced.
- Make "ON_EXCEPTION_RETURN_VALUES" dict a config. Give users the option to configure the "normalization" from scrape_me as they find fit.


2) Returning None in our default config wins my vote given the above.

If you agree with the above I can dev it this weekend and submit PR for review.

👍

**Comment by jayaddison** [comment]
This sounds like really promising set of changes.  Glad to help out with code review and feedback as a potential early adopter of an updated version :)

**Comment by bfcarpio** [comment]
That sounds really good. If you want to make a first shot at doing the error handling I can look through the existing custom scraper implementations and try to standardize them to returning `None` by default. Let me know what branch you use and we can try to merge everything together into one PR that solves this issue.

Ideally, I'm hoping that we can do the error handling outside of the metaclass for #317 , but we can stick to one breaking change at a time :sweat_smile:

**Comment by bfcarpio** [comment]
Closing this because we've solidified our conventions. From my understanding they are as follows:
+ Throw exceptions by default
  - Catch exceptions and re-raise our `RecipeScrapersExceptions` where possible.
+ Allow for additional functionality across the scraper via metaclasses.

Now that we've done this I think I can contribute a bit more documentation.
