### ISSUE TITLE
Links Function

### ISSUE THREAD

**Issue by mbgregory** [hhursev/recipe-scrapers#32]
I am using this project as the foundation for a web crawler to collect recipe data for a Natural Language Processing project I am working on. Would you accept a pull request that adds the ability to return the links that reference that calling domain?

**Comment by hhursev** [comment]
Yes, it will be accepted :) Feel free to add that method to the `exclude_lines` section in the (.coveragerc)[https://github.com/hhursev/recipe-scrapers/blob/master/.coveragerc#L10] too.

Thanks for contributing!
