### ISSUE TITLE
Consider handling preparation times and cooking times separately

### ISSUE THREAD

**Issue by jayaddison** [hhursev/recipe-scrapers#326]
Although there's a lot of scope for handling time-related concepts in recipes, the time values that appear most often seem to be:

* Preparation time (getting ingredients and kitchen ready)
* Cooking time (time combining the ingredients into a resulting meal)
* Total time (sum of each of the above)

Currently we tend to only return the total time (do we?  I think we do; is it formalized?) - but it could be useful to separate out different preparation and cooking times when available.

To maintain backwards-compatibility and reduce migration challenges we'd likely want to ensure that existing time values are maintained (I think - again it may depend a little on what the current time values we return are intended to mean).

**Comment by bfcarpio** [comment]
I've always interpret it as the sum... Maybe we should have functions for prep time and cooking time able to be overridden and then we wrap them for `total_time()`.

**Comment by smilerz** [comment]
I'd like to add my support for collecting all of the time components separately when they exist.
Some sites also include 'wait time' instead of 'cooking time'

**Comment by jayaddison** [comment]
Resolved by #416.
