### ISSUE TITLE
String Normalizer Does Not Strip HTML Tags

### ISSUE THREAD

**Issue by jksimoniii** [hhursev/recipe-scrapers#345]
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**
  - https://www.delish.com/cooking/recipe-ideas/recipes/a54115/garlicky-greek-chicken-recipe/

**The version of Python you're using**
Python 3.7

**The operating system of your environment**
Linux Mint

**The results you expect to see**
No HTML tags after calling `normalize_string`

**The results (including any Python error messages) that you are seeing**
```
3 tbsp. <p>extra-virgin olive oil, divided</p>
<p>Juice of 1 lemon</p>
3 <p>cloves garlic, minced</p>
1 tsp. <p>dried oregano</p>
1 lb. <p>chicken thighs</p>
<p>kosher salt</p>
<p>Freshly ground black pepper</p>
1/2 lb. <p>asparagus, ends removed</p>
1 <p>zucchini, sliced into half moons</p>
1 <p>lemon, sliced</p>
```

Can you write Python and would you like to help fix the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [x] I'd like to try fixing this scraper myself
- [ ] I'd like guidance to help me develop a fix
- [ ] I'd prefer if the `recipe-scrapers` team try to fix this

**Comment by hhursev** [comment]
Closing as this should be fixed in v13 . Reused the code from your PR and made it as a plugin
