### ISSUE TITLE
simplyrecipes.com not returning instructions

### ISSUE THREAD

**Issue by bswift86** [hhursev/recipe-scrapers#347]
Thanks for filing a bug report with us!

If your request is about a website that is not supported, please open a 'new scraper' issue request instead.

To help get the issue fixed, please fill in the information below.

**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

https://www.simplyrecipes.com/recipes/classic_rack_of_lamb/

**The version of Python you're using**

3.9.2

**The operating system of your environment**

Windows 10

**The results you expect to see**

an array of steps from scraper.instructions()

**The results (including any Python error messages) that you are seeing**

An empty string. I've tested ingredients() with other sites and it works fine. Also, the other returns from simplyrecipes (title,yields,ingredients,etc...) work as expected.

Can you write Python and would you like to help fix the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [ ] I'd like to try fixing this scraper myself
- [ ] I'd like guidance to help me develop a fix
- [x] I'd prefer if the `recipe-scrapers` team try to fix this

Sorry! I'm not very fluent in Python, otherwise I'd love to tackle it myself.

**Comment by jayaddison** [comment]
Thanks @bswift86 - yep, I see that same issue too.  It looks like the format of the simplyrecipes.com pages has changed slightly - not a huge amount, but enough to cause problems retrieving the recipe instructions.

In case of it's useful, and for future reference, the rough steps involved in confirming and resolving the problem are:

- Retrieve the latest HTML content for a page, or pages (thanks for the link; we also have https://www.simplyrecipes.com/recipes/one_pot_chicken_and_rice_soup/ in our test dataset at the moment, so I'll likely use that)
- If appropriate, update the tests to match the expected content from the recipe (what you'd expect to see when reading it in a browser)
- Run the tests to discover what the actual results retrieved are (in this case, an empty result)
- Adjust the scraper accordingly to match the expected content
- Commit the updated tests and/or scraper code to the repository

Should hopefully have a fix for this later today.

**Comment by jayaddison** [comment]
I'm going to make a small edit to the issue title, since I think this relates to instructions rather than ingredients, as far as I can tell; please let me know if that's not the case.
