### ISSUE TITLE
Duplicate scraper: spruceeats / thespruceeats

### ISSUE THREAD

**Issue by jayaddison** [hhursev/recipe-scrapers#363]
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

I don't think this is causing any problems, but during rebase and some test expectation adjustments in #329, I noticed that we have duplicate scrapers for `spruceeats` and `thespruceeats`.

**Comment by hhursev** [comment]
oh lol. We look better when supporting more sites 😄 

`thespruceeats`  is the one we should leave as naming. And looks like spruceeats is the one we should leave codewise

**Comment by jayaddison** [comment]
:)

Sounds good - so, a two-step process:

1. Remove the existing `thespruceeats` scraper
1. Rename the existing `spruceeats` scraper to `thespruceeats`

?

(could be a good first issue for someone)
