### ISSUE TITLE
Scrape Recipe from File

### ISSUE THREAD

**Issue by smilerz** [hhursev/recipe-scrapers#368]
I'd like to be able to scrape a recipe from file (html) and leverage the existing scrapers.

Is that possible?

**Comment by bfcarpio** [comment]
You could try [serving the html](https://stackabuse.com/serving-files-with-pythons-simplehttpserver-module/) and then using the localhost url.

As a quick and janky way you could try replacing the `testhtml` file of a scraper test as long as the file comes from a supported recipe site.

As for a nice and clean solution I don't think so.

**Comment by smilerz** [comment]
i created a wrapper to accomplish this

**Comment by bfcarpio** [comment]
That's great! Feel free to share your wrapper in #9
