### ISSUE TITLE
Proposal for another site to be added to the scrapper 

### ISSUE THREAD

**Issue by Alex-Sheardown** [hhursev/recipe-scrapers#370]
Site: https://redhousespice.com/

Example recipe link: https://redhousespice.com/char-siu-chinese-bbq-pork/

**Comment by gregwa1953** [comment]
I'm in the process of adding the wild_mode to my current app that uses this wonderful scraper library.  It worked for me.

You can try something like this...

`testlink1 = "https://redhousespice.com/char-siu-chinese-bbq-pork/"
if testlink1 in s:
    print(f'{testlink1} is already done.')
else:
    print(f'Testing wildmode for {testlink1}')
scraper = scrape_me(testlink1, wild_mode=True)
title = scraper.title()
total_time = scraper.total_time()
yields = scraper.yields()
ingredients = scraper.ingredients()
instructions = scraper.instructions()
image = scraper.image()
links = scraper.links()
`

I hope this helps!
Greg
