### ISSUE TITLE
Street Kitchen blog support 

### ISSUE THREAD

**Issue by NagyGyorgyKristof** [hhursev/recipe-scrapers#399]
Hi, 

I would be grateful, If you could support this site :  https://streetkitchen.hu/

Example recipe: https://streetkitchen.hu/hust-hussal/fuszeres-rantott-karaj/

**Comment by cydanil** [comment]
As of the lastest version, [13.3.5, available here](https://github.com/hhursev/recipe-scrapers/releases/tag/13.3.5), you can import recipes from Street Kitchen:

```python
In [1]: from recipe_scrapers import scrape_me
RDFLib Version: 5.0.0

In [2]: recipe = scrape_me('https://streetkitchen.hu/hust-hussal/fuszeres-rantott-karaj/')

In [3]: recipe.title()
Out[3]: 'Fűszeres rántott karaj'
```

**Comment by jayaddison** [comment]
Thank you both @NagyGyorgyKristof for the suggestion and @cydanil for making this possible!
