### ISSUE TITLE
New site

### ISSUE THREAD

**Issue by cookiesioux** [hhursev/recipe-scrapers#40]
Could you help me with this site? its allrecipe brazilian version
http://allrecipes.com.br/

Recipe adress
http://allrecipes.com.br/receita/11219/bolo-de-iogurte-f-cil-de-liquidificador.aspx

**Comment by hhursev** [comment]
@cookiesioux , yep. added ;)

**Comment by cookiesioux** [comment]
Thanks!!! <333
