### ISSUE TITLE
Rainbow Plant Life

### ISSUE THREAD

**Issue by Serenity23** [hhursev/recipe-scrapers#404]
Please add this website:

Url: https://rainbowplantlife.com/

Recipe URL:

https://rainbowplantlife.com/vegan-brown-butter-peach-cobbler/

Thank you!

**Comment by jayaddison** [comment]
Glad to, @Serenity23 - thanks for suggesting it, that should be available soon.  If you're able to provide a recommendation for good vegan cheese(s) in return I'd be glad for those - no problem if not though!

**Comment by Serenity23** [comment]
> Glad to, @Serenity23 - thanks for suggesting it, that should be available soon. If you're able to provide a recommendation for good vegan cheese(s) in return I'd be glad for those - no problem if not though!

I'm actually not vegan LOL. But she does have some recommendations on this blog page (at the bottom): 
https://rainbowplantlife.com/the-best-vegan-cheese-substitutes-store-bought-and-recipes/

**Comment by jayaddison** [comment]
> > Glad to, @Serenity23 - thanks for suggesting it, that should be available soon. If you're able to provide a recommendation for good vegan cheese(s) in return I'd be glad for those - no problem if not though!
> 
> I'm actually not vegan LOL. But she does have some recommendations on this blog page (at the bottom):
> https://rainbowplantlife.com/the-best-vegan-cheese-substitutes-store-bought-and-recipes/

No worries :laughing: and thank you!
