### ISSUE TITLE
Recipe Scraper: New site recommended

### ISSUE THREAD

**Issue by jimcooksfoodgood** [hhursev/recipe-scrapers#407]
Hello; I would be honored if we could include jimcooksfoodgood.com to the scraper list.

**Comment by jayaddison** [comment]
Nice site, @jimcooksfoodgood - and good news for you, it looks straightforward to add, thanks to your use of Wordpress Recipe Maker.  We should have it included soon.

**Comment by jimcooksfoodgood** [comment]
Many thanks.
