### ISSUE TITLE
[Question] Batch scrape "hellofresh"

### ISSUE THREAD

**Issue by jaddel** [hhursev/recipe-scrapers#411]
How would I do a batch scrape of all recipes? 

Starting form here:

```
from recipe_scrapers import scrape_me

pagenr = 0

url =f'https://www.hellofresh.de/recipes/search/?page={pagenr}'

scraper = scrape_me(url)
```

**Comment by micahcochran** [comment]
You need a [web crawler](https://en.wikipedia.org/wiki/Web_crawler) to do that.  You'd have to define the behavior of how that crawler navigates a given website.

You can use the `scraper.links()` to get a the next links.  Please abide by `robots.txt`.

I wrote a crawler with some configuration that could dump all of those into JSON file.  I need to push an updated for the latest version.

**Comment by jaddel** [comment]
thx for your reply. 

I tryed scraper.links() on search url as mentioned in the op, but it doesn't extract the links for the individual recipes.

**Comment by micahcochran** [comment]
Check if the link's `href` startswith "https://www.hellofresh.de/recipes/".  I'd keep a list of all of those links that match the pattern.  

The crawler may have to crawl pages that have no recipe content in order to scrape all the recipes.

**Comment by micahcochran** [comment]
I've release a web crawlers that I think may do something of what you want, it is called [recipe_crawler](https://github.com/micahcochran/recipe-crawler).

You'd need to make a YAML file for https://www.hellofresh.de/recipes/  Please feel free to post and issue when you get stuck.  This project is fairly new, so it may still be a little rough around the edges.

There are still a couple of features that I'd like to put in, but it is in a pretty good state at the moment.

**Comment by jaddel** [comment]
thanks for sharing, I'll give it a try when I finde some time.

**Comment by jayaddison** [comment]
Closing a few old issues - please comment, re-open or file a new issue for any unresolved items (preferably after checking for more recent discussion!). Thank you.
