### ISSUE TITLE
Albert Heijn - ah.nl almost working

### ISSUE THREAD

**Issue by fyxtro** [hhursev/recipe-scrapers#421]
We always enjoy adding support for new websites to the library!

To help us out, please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login) and add sample recipe URL(s) below:

- https://www.ah.nl/allerhande/recept/R-R8522/kruidige-groentecalzone
- https://www.ah.nl/allerhande/recept/R-R1194797/kippendij-uit-de-oven-met-ansjovis-citroenmarinade-broccoli-en-aardappelschijfjes

Can you write Python and would you like to help add the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [ ] I'd like to try adding this scraper myself
- [ x] I'd like guidance to help me develop a scraper
- [ ] I'd prefer if the `recipe-scrapers` team try to add this

I have ran it with the provided script from the FAQ and it returns everything except for the instructions. On the webpage this is under "Aan de slag." On the first link it does not work but on the second link it does. I do not know (yet) how to fix that.

**Comment by jayaddison** [comment]
Welcome @fyxtro!  We'll be glad to help.  Could you [open a pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) with the code that you have so far?  That'll help us to discuss a way to adapt your code to handle both types of recipe.

**Comment by fyxtro** [comment]
Ah, I misinterpreted that option. I have not written anything (yet). But I ran it through the code underneath the FAQ and came across these findings.

**Comment by jayaddison** [comment]
No problem :)  I'll try to take a look at implementing this soon; I've added a couple of labels to hopefully boost the visibility of it until then.
