### ISSUE TITLE
Issue scraping seriouseats.com

### ISSUE THREAD

**Issue by cameronezell** [hhursev/recipe-scrapers#436]
example URL: [https://www.seriouseats.com/detroit-style-pizza-recipe](https://www.seriouseats.com/detroit-style-pizza-recipe)
The source of the issue appears to be that the `@type` in the schema for the site is being saved as a list (`['Recipe']` instead of a string`'Recipe'`). This becomes an issue [here](https://github.com/hhursev/recipe-scrapers/blob/a5f598b7dcc4d678515e89a5ecfc173c02e0d1f9/recipe_scrapers/_schemaorg.py#L27) where SchemaOrg is attempting to use `.lower()` on the list object instead of the string. I know that this can easily be fixed locally by changing it to `item.get("@type", "")[0].lower()` but this would also require an if statement to see if it's a string or list object. I also don't know if it would always be the case that 'Recipe' would be the first item in the list, so maybe using `.index()`? I don't know what other downstream effects this has as I'm pretty new to this project.
Hope this helps!

**Comment by jayaddison** [comment]
Thanks @cameronezell, well discovered.  It looks like it is [valid in JSON-LD](https://www.w3.org/TR/json-ld11/#example-15-specifying-multiple-types-for-a-node) for nodes (including contexts, I think) to have multiple `@type`s, so this is something we should handle.

This might also be an opportunity to refactor some of that code a little bit, if it's possible to make it more readable without causing any other problems.

And yep, agreed that we shouldn't rely on the ordering of the contents of the `@type` field (when it is a list).

I'll try to take a look at this soon unless someone else from the project gets to it first :)  (alternatively, you're also welcome to open a pull request and we could review and discuss that)
