### ISSUE TITLE
Error scraping ingredients on allrecipes.com source

### ISSUE THREAD

**Issue by kleinjm** [hhursev/recipe-scrapers#44]
Not sure how widespread this error is (everything on the domain or just this one recipe) but I have an automated test suite in a rails app that runs this script and it just started failing.

```py
from recipe_scrapers import scrape_me
import sys
import json

try:
    # give the url as a string, it can be url from any site listed below
    scrape_me = scrape_me(str(sys.argv[1]))

    # data = {
    #     "title": scrape_me.title(),
    #     "total_time": scrape_me.total_time(),
    #     "ingredients": scrape_me.ingredients(),
    #     "instructions": scrape_me.instructions()
    # }

    print(scrape_me.ingredients())

    # with open('tmp/recipe_data.json', 'w') as outfile:
    #     json.dump(data, outfile)
except:
    print("Error while scraping recipe", sys.exc_info())

```
Seeing
```
('Error while scraping recipe', (<type 'exceptions.UnicodeDecodeError'>, UnicodeDecodeError('ascii', '\xa0', 0, 1, 'ordinal not in range(128)'), <traceback object at 0x11145b6c8>))
```
for url https://www.allrecipes.com/recipe/45736/chicken-tikka-masala/?internalSource=hub%20recipe&referringId=2264&referringContentType=recipe%20hub&clickId=cardslot%2013

`.title()` and `.total_time()` work but via commenting out I traced it back to `.ingredients()` causing the issue. I'm not a python dev so I didn't dig any deeper.

**Comment by hhursev** [comment]
Can you tell me which Python version is this? 

I’d advise you to name things such as:
```
scraper = scrape_me(str(sys.argv[1]))
scraper.ingredients()  # title / instructions / etc.
```
not to overwrite the package namespace.

Also, can you check if a quick update on the line with the file opening to:
```
 with open('tmp/recipe_data.json', 'w', encoding='utf-8') as outfile:
```
resolves the issue

**Comment by kleinjm** [comment]
```sh
> python --version
Python 2.7.15
```

No luck with the encoding change, seems to break before file writing.

Here's [the script in the full project](https://github.com/kleinjm/recipe_viewer/blob/master/lib/recipe_scraper.py). To reproduce I first install the requirements (`pip install -r requirements.txt`) then run the following.

```sh
python lib/recipe_scraper.py "https://www.allrecipes.com/recipe/45736/chicken-tikka-masala/?internalSource=hub%20recipe&referringId=2264&referringContentType=recipe%20hub&clickId=cardslot%2013"
```

**Comment by hhursev** [comment]
The package does not support python 2, nor does it intend to.

If you can switch to Python3 this will be the best thing to do. I expect the encoding issue to be resolved too.

However, if you really want to stick with Python2 let me know and I'll write you a gist with a fix.

**Comment by kleinjm** [comment]
That did it! I know what the cause was. 

I recently moved `pyenv init` from  .zshrc to .zshenv to fix a script in a non-interactive shell. Looks like that didn't work though. I was following the line
> Zsh note: Modify your ~/.zshenv file instead of ~/.bash_profile

From https://github.com/pyenv/pyenv#basic-github-checkout

Sorry to bother and thanks for the help and fast reply as always!
