### ISSUE TITLE
Getting an error with the total_time() function for bbcgoodfood.py

### ISSUE THREAD

**Issue by directfrog** [hhursev/recipe-scrapers#446]
There is an exception being raised:

 raise SchemaOrgException("Cooktime information not found in SchemaOrg")
 recipe_scrapers._exceptions.SchemaOrgException: recipe-scrapers exception: Cooktime information not found in SchemaOrg

I ran the total_time() funtion on recipes in the  following link:
 https://www.bbcgoodfood.com/recipes/collection/eggy-bread-recipes

I also get similar exceptions for the cook_time() and prep_time() functions however there are no problems with the other functions like ingredients() or instructions(). Would it be possible to change the code up a little to make it work?

**Comment by jayaddison** [comment]
Thanks for the issue report, @directfrog!  I didn't see the exception after scraping a couple of the recipes on that page -- could you provide the URL of one where the exception occurs for you?

**Comment by Makanz** [comment]
I have also lookt at this and the only problem i find is with the link provided. Thats because it´s a collection of recipies and not only one recipie.
