### ISSUE TITLE
Woolworths.com.au

### ISSUE THREAD

**Issue by jfgonsalves** [hhursev/recipe-scrapers#447]
Hi all,

I'd like to get Woolworths.com.au scraping working. It looks like the site does serve up schema so I'm not sure why the parser can't pick it up in wild mode.

- https://www.woolworths.com.au/shop/recipes/asparagus-salad-with-lemon-vinaigrette

I'm learning how to write Python so, assuming this isn't something that just needs a small tweak to work in Wild Mode, I'd be keen to give it a crack.

Thanks!

- [ ] I'd like to try adding this scraper myself
- [X] I'd like guidance to help me develop a scraper
- [ ] I'd prefer if the `recipe-scrapers` team try to add this

**Comment by jfgonsalves** [comment]
Okay, so it looks like the JSON is injected into the HTML by some Javascript when the page is run. I suspect that means the scraper won't have access to the JSON - I'll try and follow the instructions to scrape the data from the HTML unless someone has any other ideas?

**Comment by jayaddison** [comment]
Yep, that sounds like a reasonable approach @jfgonsalves.  `recipe-scrapers` doesn't have the ability to evaluate JavaScript from web pages at the moment, so you'll likely have some details to figure out there.

Currently the scrapers accept (at least) [a URL parameter as input](https://github.com/hhursev/recipe-scrapers/blob/8a9672166b67d91986bca3e58fceb863cecb37bb/recipe_scrapers/_abstract.py#L22), but we could consider modifying the scraper interface to accept page content as well as -- or instead of -- that.

**Comment by bfcarpio** [comment]
@jayaddison I just found [this package](https://github.com/psf/requests-html) that seems to be able to handle some javascript rendered content. Unsure how this will work for embedded content.

**Comment by micahcochran** [comment]
Related issue #193

**Comment by jayaddison** [comment]
> @jayaddison I just found [this package](https://github.com/psf/requests-html) that seems to be able to handle some javascript rendered content. Unsure how this will work for embedded content.

That's impressive!  It downloads and then uses a local instance of Chromium to achieve this, by the [sounds of it](https://github.com/psf/requests-html/blob/026c4e5217cfc8347614148aab331d81402f596b/README.rst#javascript-support).

One challenge we might run into: evaluating JavaScript could involve additional network requests per page, whereas currently we only require a single GET.

**Comment by C-Sto** [comment]
sorry, beat you to it @jfgonsalves It was a little more complicated that modifying Wild mode. No need for js execution, just some hacky url parsing and digging around in json
