### ISSUE TITLE
Please enhance support for lecker.de. Not all recipes can be parsed

### ISSUE THREAD

**Issue by ordo01** [hhursev/recipe-scrapers#448]
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [ ] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://www.lecker.de/naan-brot-backen-so-geht-das-rezept-72968.html

**The version of Python you're using**
Python 3.9
**The operating system of your environment**
Used as part of https://github.com/TandoorRecipes/recipes
...

**The results you expect to see**
"The requested site provided malformed data and cannot be read."

Other recipes from the same site work fine, for example https://www.lecker.de/indischer-gemuesereis-mit-roestzwiebeln-71097.html

Can you write Python and would you like to help fix the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [ ] I'd like to try fixing this scraper myself
- [X] I'd like guidance to help me develop a fix
- [] I'd prefer if the `recipe-scrapers` team try to fix this

**Comment by vabene1111** [comment]
looks like an issue similar to #366 as lecker.de seems to have structured data on some pages and doesnt on others. 

will implement a similar fix, PR will follow tomorrow
