### ISSUE TITLE
Question on how to parse / what goes into intructions

### ISSUE THREAD

**Issue by lionawurscht** [hhursev/recipe-scrapers#45]
Hey, I was trying to write a scraper for recipes created with the wordpress recipe maker but am unsure about what should go into intructions.
example: [soft-baked-gingerbread-cookies](https://www.tastesoflizzyt.com/soft-baked-gingerbread-cookies/)

I have two questions about it:
1. Should instructions that come in a numbered list maintain those numbers or just be joined with newlines? I feel like dropping the numbers removes some of the information from the original.
2. Should supplementary information, such a notes also go into instructions? In some cases this seems to make more sense then in others, e.g. when the notes contain possible substitutions vs. when they just contain some sort of story about the recipe.

Generally it might be helpful to specify these things somewhere, don't you think?

**Comment by micahcochran** [comment]
This wordpress site uses [schema.org/Recipe](https://schema.org/Recipe) format.

Alternatively, you could use [scrape-recipe-schema](https://github.com/micahcochran/scrape-schema-recipe) instead.  Just a suggestion.

```Python
In [1]: import scrape_schema_recipe

In [2]: recipes = scrape_schema_recipe.scrape_url('https://www.tastesoflizzyt.c
   ...: om/soft-baked-gingerbread-cookies/')

In [4]: recipes[0]['recipeInstructions']
Out[4]:
[{'@type': 'HowToStep',
  'text': 'In a large bowl, cream together the shortening, brown sugar, molasses
 and buttermilk.'},
 {'@type': 'HowToStep',
  'text': '&nbsp;In a separate bowl, sift together the flour, baking soda, ginge
r, cinnamon, nutmeg, cloves and salt.&nbsp;'},
 {'@type': 'HowToStep',
  'text': 'Add the dry ingredients to the creamed sugar mixture and mix well.&nb
sp;'},
 {'@type': 'HowToStep',
  'text': 'Roll the dough into balls and then roll the balls in sugar.'},
 {'@type': 'HowToStep',
  'text': 'Place the cookie dough balls on an ungreased cookie sheet and bake at
 350 degrees for 11-12 minutes.'},
 {'@type': 'HowToStep',
  'text': 'Allow the cookies to cool on a wire rack and then store in an airtigh
t container.'}]
```

**Comment by lionawurscht** [comment]
Ah thank you, that's a better solution of course :+1: 
I'll look into it.
