### ISSUE TITLE
Serious Eats scraper not working

### ISSUE THREAD

**Issue by sckilcoyne** [hhursev/recipe-scrapers#450]
Thanks for filing a bug report with us!

If your request is about a website that is not supported, please open a 'new scraper' issue request instead.

To help get the issue fixed, please fill in the information below.

**Pre-filing checks**

- [/] I have searched for open issues that report the same problem
- [using latest docker image] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://www.seriouseats.com/bravetart-homemade-cinnamon-rolls-recipe

**The version of Python you're using**

...

**The operating system of your environment**
Docker/linux?
...

Getting ingredients and instructions with "Could not detect ingredients/instructions". I'd expect to see the actual info.

...

**The results (including any Python error messages) that you are seeing**

...

Can you write Python and would you like to help fix the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [ ] I'd like to try fixing this scraper myself
- [ ] I'd like guidance to help me develop a fix
- [/ ] I'd prefer if the `recipe-scrapers` team try to fix this
(At some point in the future I'd be willing to learn to try to help)

**Comment by cadamswaite** [comment]
This should be fixed by #438
