### ISSUE TITLE
Betty Crocker recipes not adding

### ISSUE THREAD

**Issue by reg-brink** [hhursev/recipe-scrapers#458]
Importing from bettycrocker.com, specifically https://www.bettycrocker.com/recipes/banana-bread/51427396-6764-4b0a-a73a-78c683c703d2?fbclid=IwAR19P9TitTkqoebU04dVQc3PAw3C72FxJxP0GDC8xzCG9jvBIm75ItwWYAY, does not load the ingredients or steps.

Thanks

**Comment by jayaddison** [comment]
Thanks @reg-brink - could you confirm the version of `recipe-scrapers` that you're seeing this problem with?

**Comment by danich1** [comment]
Can confirm this issue for bettycrocker webpage: https://www.bettycrocker.com/recipes/banana-bread/51427396-6764-4b0a-a73a-78c683c703d2. Version number 13.10.0 (most recent version).

Current Code is checking for 
```html
div class "recipePartIngredientGroup"
```
but the website has ingredients under: 
```html
div class:"recipeIngredients primary"
```
Feel free to go to page and check out the source code at line 1252.

**Comment by jayaddison** [comment]
Thank you @danich1!  That led directly to the required fixes here.  Pull request #475 is now open with some changes that should resolve this problem.

(note that retrieval of `ratings` also seemed to be broken and that's been fixed up at the same time)
