### ISSUE TITLE
More scrapers request

### ISSUE THREAD

**Issue by kleinjm** [hhursev/recipe-scrapers#46]
I have a [recipe app](http://recipes.jamesmklein.com/) (for personal use) that uses your scrapers and I just built a dashboard to see what sites I use the most. Here's a list of the top ones that I use. So this isn't actually an issue, just a passive request to add any missing ones to the list if you have the time. Thanks again for such a great tool!

![image](https://user-images.githubusercontent.com/2565158/49342539-b3c6a700-f62a-11e8-8c2e-c856340a0623.png)

**Comment by marcolussetti** [comment]
Hacktoberfest is always a good opportunity to add more sites to the project, I think, so converting this to a list:

- [ ] cookiesandkate.com
- [ ] thekitchn.com
- [ ] bonappetit.com
- [ ] foodnetwork.com
- [ ] allrecipes.com
- [ ] seriouseats.com
- [ ] countryliving.com
- [ ] myrecipes.com
- [ ] delish.com
- [ ] geniuskitchen.com
- [ ] ohsheglows.com
- [ ] twopeasandtheirpod.com
- [ ] simplyquinoa.com
- [ ] cooking.nytimes.com
- [ ]momswithcrockpots.com

**Comment by kleinjm** [comment]
Much appreciated. I have moved off the project that uses this library as a dependency but thanks again for all the great work

**Comment by klebinhopk** [comment]
Could not create a scrapper for the site **https://www.tudogostoso.com.br** ???

**Comment by PatrickPierce** [comment]
Updated list. Removed genuiskitchen.com (Owned by food.com now)

- [x]  cookieandkate.com
- [x] thekitchn.com
- [x] bonappetit.com
- [x] foodnetwork.com
- [x] allrecipes.com
- [x] seriouseats.com
- [x] countryliving.com
- [ ] myrecipes.com
- [x] delish.com
- [ ] ohsheglows.com
- [ ] twopeasandtheirpod.com
- [x] simplyquinoa.com
- [ ] cooking.nytimes.com
- [x] momswithcrockpots.com

**Comment by kleinjm** [comment]
Awesome, thank you so much!
