### ISSUE TITLE
Serious eats error with yield class being renamed to serving

### ISSUE THREAD

**Issue by drewtownchi** [hhursev/recipe-scrapers#463]
Thanks for filing a bug report with us!

If your request is about a website that is not supported, please open a 'new scraper' issue request instead.

To help get the issue fixed, please fill in the information below.

**Pre-filing checks**

- [x ] I have searched for open issues that report the same problem
- [x ] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://www.seriouseats.com/spaghetti-with-canned-clam-sauce

It looks like they've changed the class name to recipe-servings from recipe-yield

**The version of Python you're using**
3.9.9
...

**The operating system of your environment**
Windows 10
...

**The results you expect to see**
The correct servings yield from serious eats
...

**The results (including any Python error messages) that you are seeing**
 line 21, in yields
    self.soup.find("div", {"class": "recipe-yield"}).find(
AttributeError: 'NoneType' object has no attribute 'find'
...

Can you write Python and would you like to help fix the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [x ] I'd like to try fixing this scraper myself
- [ ] I'd like guidance to help me develop a fix
- [ ] I'd prefer if the `recipe-scrapers` team try to fix this

**Comment by drewtownchi** [comment]
Looking into this a bit more it seems that seriouseats uses both yield and servings. Something can yield 2 pies but serves 20.  This data seems to be in their ld+json as well for both yield and servings but I'm not sure if we can use those.

I think based on how most other websites show yield we probably actually want to use the "servings" data as that is most similar to other websites.

**Comment by jayaddison** [comment]
Thanks for looking into this @drewtownchi - I'd agree with your view of this; we tend to prefer to return servings, and fall back to yields when servings is not available.

For safety and backwards-compatibility we should probably try `recipe-servings` first, then `recipe-yield` as a fallback if that's not found.

I'll try to take a look at this later today, hopefully it's a smallish change.
