### ISSUE TITLE
Unit test output noise: JSONDecodeError

### ISSUE THREAD

**Issue by jayaddison** [hhursev/recipe-scrapers#464]
When running the unit tests, there's a bunch of noise from JSON decoding errors that we could/should suppress.

For example, from [this build's output](https://github.com/hhursev/recipe-scrapers/runs/4493368275?check_suite_focus=true#step:6:25).

```
ERROR:extruct._extruct:Failed to extract json-ld, raises Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/extruct/_extruct.py", line 108, in extract
    output[syntax] = list(extract(document, base_url=base_url))
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/extruct/jsonld.py", line 27, in extract_items
    for items in map(self._extract_items, self._xp_jsonld(document))
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/extruct/jsonld.py", line 28, in <listcomp>
    if items for item in items if item
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/extruct/jsonld.py", line 38, in _extract_items
    data = jstyleson.loads(HTML_OR_JS_COMMENTLINE.sub('', script), strict=False)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/jstyleson.py", line 123, in loads
    return json.loads(dispose(text), **kwargs)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jayaddison** [comment]
Hrm.  This is a little more tricky than expected.

This noise is generated by `extruct` and can be suppressed by setting `errors='ignore'` [here](https://github.com/hhursev/recipe-scrapers/blob/e7ce79b3d160c5ff18bd73434341bd6bb791d13a/recipe_scrapers/_schemaorg.py#L25).

However I don't think we should suppress `extruct` logs for _all_ scraper unit tests globally -- because they could help developers to more quickly learn about and diagnose problems.

So I considered adding this as a per-scraper boolean flag to the [`ScraperTest` base class](https://github.com/hhursev/recipe-scrapers/blob/e7ce79b3d160c5ff18bd73434341bd6bb791d13a/tests/__init__.py#L7) (and then individual tests -- like [`thespruceeats_1`](https://github.com/hhursev/recipe-scrapers/blob/e7ce79b3d160c5ff18bd73434341bd6bb791d13a/tests/test_thespruceeats_1.py#L5) which is affected by this).  I considered using `suppress_extruct_logs = False` as the name and default.

However.. that would then have to be piped through the [`AbstractScraper` constructor as an additional parameter](https://github.com/hhursev/recipe-scrapers/blob/e7ce79b3d160c5ff18bd73434341bd6bb791d13a/recipe_scrapers/_abstract.py#L20-L28), and I don't think it's something we want in the public `recipe-scrapers` library API.

**Comment by hhursev** [comment]
I'd steer into the direction of adding the errors='ignore' setting if our LOG_LEVEL is above some threshold 

```
import settings
from recipe_scrapers.settings import settings

settings.LOG_LEVEL >= logging.INFO
```

directly into the AbstractScraper. We don't want to bother users using the library with logs like you posted above I agree.

**Comment by jayaddison** [comment]
Hrm.. I kinda agree, although at the same time I think we should encourage any noise that does appear during scraping to be visible to users (so that they report it back to us, and they/we can investigate & fix it).

(I'd only want to suppress this specific noise for this specific scraper because it seems to be something odd about the schema on the SpruceEats site -- ideally we'd also add some kind of test/flag that would tell us to remove the suppression once the noise disappears)

**Comment by jayaddison** [comment]
I didn't notice when this was fixed, but it doesn't seem to be an issue any more - no more noisy JSON output from the unit tests :tada:
