### ISSUE TITLE
Scraping recipe images

### ISSUE THREAD

**Issue by buneme** [hhursev/recipe-scrapers#47]
Is there a reason why recipe images are not scraped?

**Comment by hhursev** [comment]
Nope, not a specific reason.

I used this package in a project of mine and recipe images were not a priority.

That being said, there are people requesting Ratings scraping, Comments scraping so Images also make sense.

A probable course for this package is making “Extensions” section where these things can be implemented by guide without breaking the main package or making it inconsistent.

However, I cannot promise you when this will happen. If you are in a hurry to get Images data, I’d advise you to fork the repo and do as you find fit for now.

**Comment by buneme** [comment]
Understandable, I'll fork for now then, thanks!
