### ISSUE TITLE
Way to pass html content to `AbstractScraper` constructor

### ISSUE THREAD

**Issue by NikhilMJain** [hhursev/recipe-scrapers#472]
Currently, the web request is made within the constructor. Since the request is synchronous, I'm not able to use async methods. 

Can we either:
1. Add async support to the crawler
2. Add a way to pass crawled html content and let the parsers build the soup from passed html.

In method 2, I can fetch the html asynchronously and pass it to (for example) `scrape_me` function , which can then parse it synchronously.

Thoughts?

**Comment by bfcarpio** [comment]
I haven't work extensively with async in python to volunteer adjusting the entire library to supporting both async and sync style. However, it might be easier if we allow passing a function to do the scrape in a functional programming style? So as long as the scraped data is given to the constructor in a sync style then you can implement the request any way you like.

What are you opinions on this?

**Comment by NikhilMJain** [comment]
> So as long as the scraped data is given to the constructor in a sync style then you can implement the request any way you like.
Yes. This should work and is easier. 

> it might be easier if we allow passing a function to do the scrape in a functional programming style
Passing a function to which class/function? I did not quite get this. Are we passing both a function and crawled data?

Can we have a `crawled_data` optional parameter in the constructor? Then inside the constructor we check if this is `None`.

If `None`, we crawl the data (like the existing flow). If it is not `None`, then we assign this to `self.page_data` and skip the crawl within constructor.

**Comment by bfcarpio** [comment]
I was thinking something make a `make_request` function. By default it's implementation would be what we currently have. You could override it with your special implementation and then the constructor would call `make_request(url)`.

**Comment by NikhilMJain** [comment]
In this case, if I have to make use of any async method within `make_request`, then `make_request` would also have to be declared as `async` like so.

```
async def make_request(url: str) -> Response:
```
So if method `A` calls method `B`, `B` calls `C`, `C` calls `make_request`, then all `A`, `B`, `C` and `make_request` would need to be declared as async (if I use any async request maker inside `make_request`)

In this case, if the constructor calls make_request then it would have to be `await`ed like so `await make_request(url)`. 

But a constructor cannot be declared as async.

**Comment by bfcarpio** [comment]
I understand now. Yes, I agree, being able to pass in pre-scraped data would be the way to go then. This might be the best time to use a factory method that overrides the class instance's attributes?

If you draw up a PR, I'll be happy to bounce ideas with you. Actually, a super simple async example would help with testing if you're willing.

**Comment by NikhilMJain** [comment]
Yes. I'll open a PR when I get some time. Over the weekend most probably.

**Comment by hhursev** [comment]
High chance I am able to look into this in February too 😉

**Comment by hay-kot** [comment]
Hey, wanted to check in to see if this went anywhere? I'd like to be able to pass the html directly. Would adding a top level method to the package be acceptable? Something like this where you could optionally pass the domain to use one of the predefined scrapers?

```python
def scrape_html(text: str, url: str | None = None):
    ...
```

Happy to work out a PR for this.

**Comment by bfcarpio** [comment]
@hay-kot I'd highly recommend working on a PR for this!
