### ISSUE TITLE
scraping from koket.se seems to be broken

### ISSUE THREAD

**Issue by kpontussvensson** [hhursev/recipe-scrapers#476]
Thanks for filing a bug report with us!

If your request is about a website that is not supported, please open a 'new scraper' issue request instead.

To help get the issue fixed, please fill in the information below.

**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://www.koket.se/mitt-kok/tommy-myllymaki/myllymakis-toast-skagen

**The version of Python you're using**

python:3.9-alpine3.12

**The operating system of your environment**

Docker on Unraid (running TandoorRecipes which in turn use your library)

**The results you expect to see**

["as an example of what's wrong - the scrape.ingredients() should return a list of text strings like:"](https://github.com/TandoorRecipes/recipes/issues/1181#issuecomment-1006156453)

```
"1 kg räkor med skal"
```

**The results (including any Python error messages) that you are seeing**

It returns an object instead like:

```
{'id': 10543, 'name': 'räkor med skal', 'plural': None, 'type': 'ingredient', 'preparation': None, 'comment': 'gärna färska av fin kvalitet', 'alternative_amount': None, 'unit': 'kg', 'amount_info': {'to': None, 'from': 1, 'approximate': None, 'optional': None}}"
```

Can you write Python and would you like to help fix the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [ ] I'd like to try fixing this scraper myself
- [ ] I'd like guidance to help me develop a fix
- [x] I'd prefer if the `recipe-scrapers` team try to fix this

---

I reported the [issue](https://github.com/TandoorRecipes/recipes/issues/1181) over on [TandoorRecipes](https://github.com/TandoorRecipes/recipes/) first since I couldn't import a recipe from koket.se but were told the issue lies on you guys since they use your library for scraping.

Thanks for looking into this! :)

**Comment by jayaddison** [comment]
Funny; at least going by the test data we hold, it seems that Koket used to render ingredient information as objects (instead of strings) in the schema.org metadata on the page.  Perhaps that has inverted since then.  Requires a bit more investigation.

**Comment by kpontussvensson** [comment]
Yes it seems to have changed if that was the case before. I've looked at a couple of older recipes and viewing the schema.org metadata has only been strings on all of the ones I've seen so far.
