### ISSUE TITLE
https://www.franzoesischkochen.de/

### ISSUE THREAD

**Issue by juergene52** [hhursev/recipe-scrapers#477]
May I ask you to setup a recipe-scraper for site https://www.franzoesischkochen.de/. A recipe is e.g. https://www.franzoesischkochen.de/tourte-mit-feigen-und-confit-de-canard/
Thanks.

**Comment by jayaddison** [comment]
Thanks for the site suggestion - franzoesischkochen is added in #478, and should be available in `recipe-scrapers` soon.

If you have any personal connection with the site: they have one small format issue with the author 'name' field in their recipe page data:

Generally the author name field should be all-lowercase ('name') and it currently is initial-uppercase ('Name'); it's an understandable and small problem and not difficult for us to accommodate.

It might help the site's traffic (and authorship information) from other search engines and recipe collections to use the all-lowercase field name instead.
