### ISSUE TITLE
Request: Scraper for Joshua Weissman

### ISSUE THREAD

**Issue by jasonmicron** [hhursev/recipe-scrapers#483]
Site and sample recipe is here:

https://www.joshuaweissman.com/post/making-the-burger-king-whopper-at-home-but-better

Thanks, awesome tool!

**Comment by jayaddison** [comment]
This is now available in [version 14.54.0](https://pypi.org/project/recipe-scrapers/14.54.0/), also published PyPi.  Please note that there are a few known issues/limitations (#983, #984, #985) related to complexity on some recipe pages.

**Comment by jasonmicron** [comment]
Thanks, can't wait to check it out! And thanks for considering my request! Keep up the great work.
