### ISSUE TITLE
Request: EatThisMuch.com

### ISSUE THREAD

**Issue by jakern** [hhursev/recipe-scrapers#487]
We always enjoy adding support for new websites to the library!

To help us out, please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login) and add sample recipe URL(s) below:

- https://www.eatthismuch.com/recipe/nutrition/beef-casserole,33534/

Can you write Python and would you like to help add the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [ ] I'd like to try adding this scraper myself
- [X] I'd like guidance to help me develop a scraper
- [ ] I'd prefer if the `recipe-scrapers` community try to add this

I gave this a try but the directions list are not in the schema. Do you have an example of how to parse them?

**Comment by jayaddison** [comment]
Hi @jakern - that's a cool recipe site, thanks.

And yep, well spotted - it looks like a bunch of the recipe details displayed to the user are retrieved by an API call to https://www.eatthismuch.com/api/v1/recipe/33534/ after the browser loads the initial page.

The Woolworths scraper added by @C-Sto handles a similar situation by making a [second request during the scraper constructor](https://github.com/hhursev/recipe-scrapers/pull/456/files#diff-28e5adf08c654f097d51887fbf00c93bd5c973b700fe158fef1a1362eb0acd25R33-R37).  Let me know if & when I can add some more guidance.

**Comment by AdityaSoni19031997** [comment]
https://www.eatthismuch.com/api/v1/recipe/ -- this has data that we can get directly and we can adjust the offset and limit as well to gracefully scrape the website?

Thanks!

**Comment by jakern** [comment]
I'm stuck because now I'm only using the API to fetch data and I don't seem to need the AbstractScraper at all. This leads to the ScaperTest not behaving correctly because there's nothing to parse. I'm not sure I want to do away with that as well. If I do initialize the AbsractScraper, lxml fails to parse the json test file though the woolworth test file is json and doesn't have this issue.

https://github.com/jakern/recipe-scrapers/commit/1e6304353b2433b857612c5dd0f20494ceaa021d

**Comment by jayaddison** [comment]
Support for these recipes has been added, as part of #1237.
