### ISSUE TITLE
Adding support for joshuaweissman.com

### ISSUE THREAD

**Issue by reesekneeland** [hhursev/recipe-scrapers#490]
recipe link: https://www.joshuaweissman.com/post/the-perfect-rice-recipe-spanish-paella
Thank you for continuing to maintain this <3

**Comment by jayaddison** [comment]
Looks like a cool recipe site, thanks @reesekneeland.  I'll note in advance that Wix doesn't seem to make it easy to retrieve the image content related to each recipe, so that aspect could be challenging.  We'll see what we can do though.

**Comment by tom-anders** [comment]
notanothercookingshow.tv looks like it's also based on Wix. I looked through the network requests and the relevant call seems to be something like `curl 'https://www.notanothercookingshow.tv/_api/communities-blog-node-api/_api/posts/content/spicy-red-pepper-pasta?fieldsets=categories,owner,likes,content,subscriptions,tags,seo,translations,urls'`

However, this returns `{"error":"Instance is required","errorCode":7,"message":"Instance is required","traceId":"1694514092.080699187185712783"}%` - When I look in the browser, it somehow knows about this instance, but I don't know where it got it from

**Comment by jayaddison** [comment]
This is now available in [version 14.54.0](https://pypi.org/project/recipe-scrapers/14.54.0/), also published PyPi.  Please note that there are a few known issues/limitations (#983, #984, #985) related to complexity on some recipe pages.
