### ISSUE TITLE
Handle fractions and decimals in get_minutes() 

### ISSUE THREAD

**Issue by smilerz** [hhursev/recipe-scrapers#499]
current the get_minutes() utility fails to hour durations when parsing duration attributes.
Examples
- "1.5 hours"
- "1 1/2 hours"
- "1½ hours"
I believe the code below works, but can is probably inefficient and I'm not confident on the full ramifications elsewhere in the code or which corner cases would introduce further defects.

```
from unicodedata import decomposition
TIME_REGEX = re.compile(
        r"(\D*(?P<hours>\d*.?(\s\d)?\/?\d+)\s*(hours|hrs|hr|h|óra))?(\D*(?P<minutes>\d+)\s*(minutes|mins|min|m|perc))?",
        re.IGNORECASE,
    )

def get_minutes(element, return_zero_on_not_found=False):
    if element is None:
        # to be removed
        if return_zero_on_not_found:
            return 0
        raise ElementNotFoundInHtml(element)

    try:
        return int(element)
    except Exception:
        pass

    if isinstance(element, str):
        time_text = element
    else:
        time_text = element.get_text()

    if time_text.startswith("P") and "T" in time_text:
        time_text = time_text.split("T", 2)[1]
    if "-" in time_text:
        time_text = time_text.split("-", 2)[
            1
        ]  # sometimes formats are like this: '12-15 minutes'
    if " to " in time_text:
        time_text = time_text.split("to", 2)[
            1
        ]  # sometimes formats are like this: '12 to 15 minutes'

    empty = ''
    for x in time_text:
        if 'fraction' in decomposition(x):
            f = decomposition(x[-1:]).split()
            empty += f" {f[1].replace('003', '')}/{f[3].replace('003', '')}"
        else:
            empty += x
    time_text = empty
    matched = TIME_REGEX.search(time_text)

    minutes = int(matched.groupdict().get("minutes") or 0)

    if "/" in (hours := matched.groupdict().get("hours")):
        number = hours.split(" ")
        if len(number) == 2:
            minutes += 60*int(number[0])
        fraction = number[-1:][0].split("/")
        minutes += 60 * float(int(fraction[0])/int(fraction[1]))
    else:
        minutes += 60 * float(hours)

    return int(minutes)
```

- [ ] I'd like to try fixing this scraper myself
- [ ] I'd like guidance to help me develop a fix
- [x] I'd prefer if the `recipe-scrapers` team try to fix this

**Comment by hhursev** [comment]
Thanks for the input and the code samples! I reused (most) of it. If you update the package to version 13.17.0 fractions should work.

**Comment by smilerz** [comment]
> Thanks for the input and the code samples! I reused (most) of it. If you update the package to version 13.17.0 fractions should work.

Happy to contribute.  

I do have a question in that function. The line below would convert the string “hours” to “hoursoursminutes”.  Is that what is intended?  Based on the regex I wouldn’t think it was necessary at all. 

```
if "h" in time_text:
         time_text = time_text.replace("h", "hours") + "minutes"
```

**Comment by smilerz** [comment]
> Thanks for the input and the code samples! I reused (most) of it. If you update the package to version 13.17.0 fractions should work.

Happy to contribute.  

I do have a question in that function. The line below would convert the string “hours” to “hoursoursminutes”.  Is that what is intended?  Based on the regex I wouldn’t think it was necessary at all. 

```
if "h" in time_text:
         time_text = time_text.replace("h", "hours") + "minutes"
```

**Comment by hhursev** [comment]
looks like not intended! weird that it hadn't caused problems so far 😅 - will fix
