### ISSUE TITLE
monsieur-cuisine.com Picture is not in the metadata anymore

### ISSUE THREAD

**Issue by Micha10** [hhursev/recipe-scrapers#501]
URL: https://www.monsieur-cuisine.com/de/rezepte/detail/kartoffelsalat/

Python 3.9

**The results you expect to see**
I expect to see the scraped picture of the recipe

**The results (including any Python error messages) that you are seeing**
The scraper is looking in the metadata for the picture, but that information is not there anymore

**FIX**

```
   def image(self):
        container = self.soup.find("div", {"class", "flexed-image-preview"})
        container = container and container.find("figure")
        container = container and container.find('img')
        if container and container.has_attr("src"):
            container = container["src"]

        if not container:
            return None

        return "https://www." + self.host() + container

```
With that code, the URL to the picture is correct.

The test is running, because the test-html is too old

**Comment by jayaddison** [comment]
Thanks for the report and fix @Micha10 - your fix is rolled into version [13.18.1 of `recipe-scrapers`, released to PyPi](https://pypi.org/project/recipe-scrapers/).
