### ISSUE TITLE
Request for mobkitchen.co.uk

### ISSUE THREAD

**Issue by ExodosPavilion** [hhursev/recipe-scrapers#506]
We always enjoy adding support for new websites to the library!

To help us out, please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login) and add sample recipe URL(s) below:

- https://www.mobkitchen.co.uk/recipes/chilli-cheese-paratha
- https://www.mobkitchen.co.uk/recipes/caramelised-onion-linguine

Can you write Python and would you like to help add the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [ ] I'd like to try adding this scraper myself
- [x] I'd like guidance to help me develop a scraper
- [ ] I'd prefer if the `recipe-scrapers` community try to add this

**Comment by ExodosPavilion** [comment]
So it's been a while and this hasn't gotten any updates. So I figure I've got a weekend, maybe I should give a shot. However, I'm not skilled at this so some guidance would be nice.

**Comment by conor-f** [comment]
Submitted a PR actually for it: https://github.com/hhursev/recipe-scrapers/pull/515
