### ISSUE TITLE
New site request: davidlebovitz.com

### ISSUE THREAD

**Issue by vanastassiou** [hhursev/recipe-scrapers#508]
We always enjoy adding support for new websites to the library!

To help us out, please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login) and add sample recipe URL(s) below:

- https://www.davidlebovitz.com/faux-gras-foie-gras-vegetarian-lentil-mushroom-pate-recipe/

Can you write Python and would you like to help add the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [ ] I'd like to try adding this scraper myself
- [x] I'd like guidance to help me develop a scraper
- [ ] I'd prefer if the `recipe-scrapers` community try to add this

**Comment by vanastassiou** [comment]
I've gotten as far as auto-generating the class and running tests ([branch](https://github.com/vanastassiou/recipe-scrapers/tree/508-david-lebovitz-com)), but I'm running into the following error for `test_author`, `test_description`, `test_image`, `test_ingredients`, `test_instructions`, `test_title`, and `test_yields`:

```
.............ERROR:extruct._extruct:Failed to extract json-ld, raises Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/vanastassiou/repos/recipe-scrapers/.venv/lib/python3.8/site-packages/extruct/_extruct.py", line 108, in extract
    output[syntax] = list(extract(document, base_url=base_url))
  File "/home/vanastassiou/repos/recipe-scrapers/.venv/lib/python3.8/site-packages/extruct/jsonld.py", line 25, in extract_items
    return [
  File "/home/vanastassiou/repos/recipe-scrapers/.venv/lib/python3.8/site-packages/extruct/jsonld.py", line 28, in <listcomp>
    if items for item in items if item
  File "/home/vanastassiou/repos/recipe-scrapers/.venv/lib/python3.8/site-packages/extruct/jsonld.py", line 38, in _extract_items
    data = jstyleson.loads(HTML_OR_JS_COMMENTLINE.sub('', script), strict=False)
  File "/home/vanastassiou/repos/recipe-scrapers/.venv/lib/python3.8/site-packages/jstyleson.py", line 123, in loads
    return json.loads(dispose(text), **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
...............................................
```
With the test summaries all looking like this:
```
Traceback (most recent call last):
  File "/home/vanastassiou/repos/recipe-scrapers/tests/test_davidlebovitz.py", line 13, in test_author
    self.assertEqual(None, self.harvester_class.author())
AssertionError: None != 'David' # Different text on the right for each failed test, otherwise identical
```
I ran through some basic troubleshooting per [the `extruct` README](https://github.com/scrapinghub/extruct) to confirm that the recipe URL generates a valid JSON response:
```
import extruct
import requests
import pprint
from w3lib.html import get_base_url
pp = pprint.PrettyPrinter(indent=2)
r = requests.get('https://www.davidlebovitz.com/faux-gras-foie-gras-vegetarian-lentil-mushroom-pate-recipe/')
r.json()
base_url = get_base_url(r.text, r.url)
data = extruct.extract(r.text, base_url, syntaxes=['json-ld'])
data
```

**Comment by vanastassiou** [comment]
I see [Zeitwochenmarkt support](https://github.com/hhursev/recipe-scrapers/blob/main/recipe_scrapers/zeitwochenmarkt.py) includes some `extruct` behaviour modifications, so I'll have at this issue from that perspective.

**Comment by hhursev** [comment]
Hey @vanastassiou thanks for taking your time on this!

The errors you see are logging noise and not a problem. You can ignore them. If you open our [unittests logs](https://github.com/hhursev/recipe-scrapers/runs/5551667374?check_suite_focus=true) and unfold the `Unittest and Coverage Report` section you'll see that these errors are present there too (they are logging information in our case, the scrapers work properly)

I'd advise you continue with the implementation of your scraper without going down the extruct behavior modifications rabbit hole - you may not need to.

Also, you can run tests for your new scraper alone with `python -m coverage run -m unittest tests.test_davidlebovitz` - should speed up your work
