### ISSUE TITLE
Request for homechef.com

### ISSUE THREAD

**Issue by stroodle96** [hhursev/recipe-scrapers#512]
We always enjoy adding support for new websites to the library!

To help us out, please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login) and add sample recipe URL(s) below:

https://www.homechef.com/meals/prosciutto-and-mushroom-carbonara-standard 

Can you write Python and would you like to help add the scraper yourself? We'd be glad for your assistance! We can provide you with guidance and code review in return. If so, tick any of the relevant boxes below:

- [ ]  I'd like to try adding this scraper myself
- [x]  I'd like guidance to help me develop a scraper
- [x]  I'd prefer if the recipe-scrapers community try to add this

**Comment by stroodle96** [comment]
Depending on how simple this is, I would also like to make a request for everyplate.com.  But I thought I would start with homechef.  I plan to look into this a little myself.  But have very little experience with python so I am not sure how far I will get.  Any tips or advice appreciated!

**Comment by hhursev** [comment]
Hey I went ahead and implemented homechef. everyplate will be a bit more complex. We'll have to parse the html it seems feel free to open separate issue for it
