### ISSUE TITLE
Scraper not working on one of the sites

### ISSUE THREAD

**Issue by JimmyStrings** [hhursev/recipe-scrapers#523]
Hey!

I'm working on my first ever coding project and have been using the scraper to pull recipes into my python notebook. (Thanks for your hard work in building this, it's really great!).

I am raising as issue because I noticed that the package is not working on one of the listed sites. I receive an AttributeError. I think maybe the schema has changed. The website is thehappyfoodie.co.uk. Here is an example recipe URL: 

https://thehappyfoodie.co.uk/recipes/yotam-ottolenghis-ultimate-traybake-ragu/

I don't think I have the skills or experience to correct the scraper code myself. Maybe in a few months I will be able to contribute!
No problem is you don't have time to fix this, I just wanted to let you know.

Kind regards,
James

**Comment by hhursev** [comment]
Updated. Make sure you use recipe-scrapers `13.30.0` or above 😉

**Comment by JimmyStrings** [comment]
Hey again,

Sorry if I am being stupid....I checked my machine using `pip freeze` in the Command Prompt. I confirmed that I have installed recipe-scrapers 13.30.0. 

After that, I open my Jupyter Notebook and try to use the scraper on the recipe link. Here is my test code:

```
from recipe_scrapers import scrape_me

Recipe_URL = "https://thehappyfoodie.co.uk/recipes/yotam-ottolenghis-ultimate-traybake-ragu/"

scraper = scrape_me(Recipe_URL)

scraped_list = scraper.ingredients()

print(scraped_list)
```

For me, this does not return the ingredients list. I receive the following error:

AttributeError: 'NoneType' object has no attribute 'findAll'
![Capture](https://user-images.githubusercontent.com/63973463/162740511-e633caa6-d215-4d17-8163-5b33055fd6b9.PNG)

Am I doing something wrong? If you can help, I would be very grateful!

Kind regards,
James

**Comment by hhursev** [comment]
Hmmm can you run:

```
from recipe_scrapers.__version__ import __version__

print(__version__)  # should be 13.30.0
```

I think your jupiter book uses older version for some reason. (The code in the traceback is not the one from version 13.30.0)

**Comment by JimmyStrings** [comment]
You are right! Jupyter is using 13.12.1

I will find out how to fix this, thanks for your help!
