### ISSUE TITLE
Request marleyspoon.com

### ISSUE THREAD

**Issue by stroodle96** [hhursev/recipe-scrapers#534]
We always enjoy adding support for new websites to the library!

To help us out, please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login) and add sample recipe URL(s) below:

https://marleyspoon.com/menu/116120-apricot-mustard-chicken-with-asparagus-sour-cream-mashed-potatoes
https://marleyspoon.com/menu/116134-20-min-sheet-pan-fish-tacos-with-guacamole-pineapple-salsa
https://marleyspoon.com/menu/116164-20-min-cheesy-baked-gnocchi-with-broccoli-roasted-peppers

Can you write Python and would you like to help add the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [ ] I'd like to try adding this scraper myself
- [ ] I'd like guidance to help me develop a scraper
- [x] I'd prefer if the `recipe-scrapers` community try to add this

**Comment by m4rcu5** [comment]
I was taking a stab at it, but I ran into a snag. The site seems to lazy load most of the content. So for example looking for the `author-info` dive, we get the following:
```
<div class="author-info nui__col-4--tablet nui__col-6--desktop nui__column text-input__loading">
<div class="text-input__loading--line loading-item">
</div>
<div class="text-input__loading--line loading-item"></div>
</div>
```

Instead what a fully loaded page in a browser looks like:

```
          <div class="author-info nui__col-4--tablet nui__col-6--desktop nui__column">
            <p>
              Shared with you by:
              <a href="/chefs/grace-parisi">Grace Parisi</a>
            </p>
            <p>Dinner is about more than feeding my family. It's a time to decompress and open up and if i'm really lucky, it becomes a catalyst for communication and discovery. </p>
          </div>
```

Maybe some knows how to work around this?

**Comment by sbdchd** [comment]
Looking in the network tab of the page, it makes a request to an API:

```
https://api.marleyspoon.com/recipes/116120?brand=ms&country=us&product_type=web
```

but a complication is that it requires a bearer token, so a full request looks more like:

```
curl 'https://api.marleyspoon.com/recipes/116120?brand=ms&country=us&product_type=web' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJtcyIsImNvdW50cnkiOiJ1cyIsImJyYW5kIjoibXMiLCJ0cyI6MTY1MzUyNDU4NSwicmFuZG9tX2lkIjoiNmQ5Mjc1In0.LT7ApDK4GNCQtXMlhvzWvJsKKUV2XbbAZu8CsWLCRqI' \
   | jq -r '.chef.name'
```

the bearer token is a JWT with a payload of:

```
{
  "iss": "ms",
  "country": "us",
  "brand": "ms",
  "ts": 1653524585,
  "random_id": "6d9275"
}
```

So it might expire after a bit


In that case, we could pull it from the HTML content, it appears in a script tag near the bottom of the `<head`


```
<script type="text/javascript">
//<![CDATA[
window.gon={};gon.current_brand="ms";gon.current_country="us";gon.current_currency="USD";gon.env="production";gon.api_token="eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJtcyIsImNvdW50cnkiOiJ1cyIsImJyYW5kIjoibXMiLCJ0cyI6MTY1MzUyNTI3NywicmFuZG9tX2lkIjoiZDljMWIwIn0.M3o2Uo-fLD4bgCvi1LzCpFdv57YVZqlVBXQKnR5TUCI";gon.api_host="https:\/\/api.marleyspoon.com";gon.git_revision="dda3d0e";gon.recipes_preview_enabled=false;
//]]>
</script>
```
