### ISSUE TITLE
akispetretzikis scrapper

### ISSUE THREAD

**Issue by xakaitetoia** [hhursev/recipe-scrapers#537]
We always enjoy adding support for new websites to the library!

To help us out, please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login) and add sample recipe URL(s) below:

- https://akispetretzikis.com/en/recipe/608/gemista

Can you write Python and would you like to help add the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [x] I'd like to try adding this scraper myself
- [ ] I'd like guidance to help me develop a scraper
- [ ] I'd prefer if the `recipe-scrapers` community try to add this

**Comment by xakaitetoia** [comment]
Hello 👋 ,
Is there any work that will be done from developers? or what is next step?

**Comment by cydanil** [comment]
I could reproduce the issue on my setup.  
Upgrading `beautifulsoup4` resolved it for me.  
Could you check what's your version of `beautifulsoup4` (`pip freeze | grep beautifulsoup4`)?  Are you able to upgrade it?

**Comment by jayaddison** [comment]
Closing this as resolved (this scraper is working now, I believe, thanks to #564.  that fix is included in version 13.21.0 and later of this library)
