### ISSUE TITLE
Can I validate the url 

### ISSUE THREAD

**Issue by stiliajohny** [hhursev/recipe-scrapers#539]
hi all, 

Is there a way to validate the URL given on the `scrape_me` ?  

Thank you in advance 

PS : I don't mean validate the URL if it exists, but if it is having a valid recipe that can be scraped

**Comment by bfcarpio** [comment]
I believe that determining if it's a valid url that can be scraped with a recipe would require doing the network request which all happens in the scraper's `init` function. 

We'd have to move the networking functionality to somewhere else and figure out a way to reorganize things. This could be considered somewhat in line with #472.

**Comment by stiliajohny** [comment]
I managed to do a try/except, but I was hoping to see if there is something built in the library that I am missing!

**Comment by cydanil** [comment]
`recipe-scrapers` has a `SCRAPERS` dictionary that contains a list of supported urls and their associated scraper classes.  
You could use it so:  

```python
from recipe_scrapers import SCRAPERS
url = ''
url_ = urlparse(url).netloc.strip('www.')
if url_ not in SCRAPERS.keys():
    raise

**Comment by stiliajohny** [comment]
that would work !
