### ISSUE TITLE
Request kitchenstories.com

### ISSUE THREAD

**Issue by mhellmeier** [hhursev/recipe-scrapers#547]
We always enjoy adding support for new websites to the library!

To help us out, please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login) and add sample recipe URL(s) below:

- https://www.kitchenstories.com/en/recipes/spaghetti-aglio-e-olio-with-broccoli
- https://www.kitchenstories.com/de/rezepte/pasta-aglio-e-olio-mit-brokkoli (the same in german)
- https://www.kitchenstories.com/en/recipes/tiktok-s-vegan-green-goddess-salad
- https://www.kitchenstories.com/en/recipes/cauliflower-steak

Can you write Python and would you like to help add the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [ ] I'd like to try adding this scraper myself
- [ ] I'd like guidance to help me develop a scraper
- [x] I'd prefer if the `recipe-scrapers` community try to add this

-------

Some additional hints:

- There are different languages for the website available, e.g. https://www.kitchenstories.com/en/ or https://www.kitchenstories.com/de/
- It sometimes works already, but not for everything (e.g. servings are always 0)

**Comment by jayaddison** [comment]
Thanks @astappiev for offering an implementation here!  I think we'll be able to merge that soon.

@mhellmeier have you tried scraping any recipes [using `wild_mode`](https://github.com/hhursev/recipe-scrapers#faq), out of interest?
