### ISSUE TITLE
Technical debt: clean-up time-handling functions

### ISSUE THREAD

**Issue by jayaddison** [hhursev/recipe-scrapers#551]
Our time handling utility functions (particularly [`_utils.get_minutes`](https://github.com/hhursev/recipe-scrapers/blob/79e2044380d2d5a9568b76777bc7b1950dcaaeb8/recipe_scrapers/_utils.py#L32-L89) and [`_schemaorg.total_time`](https://github.com/hhursev/recipe-scrapers/blob/3fe2fd9f788e8cf3b1def24f45b5a3e5eabe2b76/recipe_scrapers/_schemaorg.py#L89-L107) have grown fairly organically with the codebase and are a bit complicated with unusual parameters and behaviours.

For example:

- If a time field in a recipe's schema is completely missing, or empty, we typically return a zero value (this seems strange?)
- As [noted](https://github.com/hhursev/recipe-scrapers/pull/549#discussion_r884916036) by @astappiev, there is a custom local method _inside_ `total_time` that provides a schema.org workaround

Depending on the cleanup, it may also be possible for us to enable an enhancement:

- In cases where any two out of three time values are present (`prep time`, `cook time`, `total time`), it should be possible to infer the missing third value

We shouldn't attempt that unless the code is clean and easy to work with - we don't want it to become more complicated than it is today.  But if we can add inference of missing values, it will be a nice extra.

**Comment by hhursev** [comment]
The way I'd like to go about this is we implement [cognitive complexity](https://www.sonarsource.com/blog/cognitive-complexity-because-testability-understandability/) measurement in our CI.

For example using https://pypi.org/project/flake8-cognitive-complexity/ might suffice. Then do the refactoring.

**Comment by jayaddison** [comment]
Thanks for the spring cleaning, @hhursev! - a virtual :beers: from here.  Using complexity scoring to guide a fix here sounds like a good approach - I'll take a look next week.

**Comment by jayaddison** [comment]
Resolved by #996.
