### ISSUE TITLE
TudoGostoso returning empty values

### ISSUE THREAD

**Issue by kkmann1** [hhursev/recipe-scrapers#56]
I tried `scraper = scrape_me('https://www.tudogostoso.com.br/receita/7778-bobo-de-camarao.html')` in python3 and none of the values are populating afterwards.

**Comment by hhursev** [comment]
Hi! Thanks for pointing this. It seems like TudoGostoso demands having javascript when you visit their site. This means this package won't support it.

You can scrap such sites with some sort of webdriver and this package does not intend to do things this way.
