### ISSUE TITLE
Update list of available variables. Return None instead of erroring

### ISSUE THREAD

**Issue by Chris230291** [hhursev/recipe-scrapers#569]
Thanks for making and maintaining this. It works great.

I noticed there are some variables available that you do not include in your example. Is this because there are issues with them or because you simply haven't updated the example yet?

Is it possible to return `None` if a variable doesn't exist instead or raising an exception?

Thanks,
Chris

**Comment by jayaddison** [comment]
Hi Chris - glad to hear the library's working well :tada: 

By default we like to distinguish between "we don't know what the value of that field is for that URL" (raise a `NotImplementedError` exception) and "the value for that field for this URL is empty" (`None` return value).

However: there is a configuration setting, [`settings.SUPPRESS_EXCEPTIONS`](https://github.com/hhursev/recipe-scrapers/blob/fa3d824b64545d3ab293da0c370c8cec9d7a04e9/recipe_scrapers/settings/default.py#L23) (disabled by default) that enables a plugin to return [default values for each unimplemented field](https://github.com/hhursev/recipe-scrapers/blob/fa3d824b64545d3ab293da0c370c8cec9d7a04e9/recipe_scrapers/settings/default.py#L27-L39) -- or `None`.

**Comment by Chris230291** [comment]
That's perfect thanks!
