### ISSUE TITLE
Add support for https://www.ethanchlebowski.com

### ISSUE THREAD

**Issue by ruudschouten** [hhursev/recipe-scrapers#574]
We always enjoy adding support for new websites to the library!

To help us out, please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login) and add sample recipe URL(s) below:

- https://www.ethanchlebowski.com/cooking-techniques-recipes/huevos-rancheros

Can you write Python and would you like to help add the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [ ] I'd like to try adding this scraper myself
- [x] I'd like guidance to help me develop a scraper
- [ ] I'd prefer if the `recipe-scrapers` community try to add this

**Comment by ruudschouten** [comment]
Oh wow, that was easier than I thought, PR can be found in https://github.com/hhursev/recipe-scrapers/pull/576

**Comment by jayaddison** [comment]
Hehe, excellent (credits due to @adamkeys for making it so easy to generate new scrapers).  I'll take a look at that pull request now.

**Comment by jayaddison** [comment]
Resolved by #576
