### ISSUE TITLE
Instructions as a list?

### ISSUE THREAD

**Issue by Chris230291** [hhursev/recipe-scrapers#575]
Hello. I was wondering if there are any reasons why you do not return instructions as a list?
I know how to convert the instructions into a list, I just imagine you don't already do that for a reason?

Chris

**Comment by jayaddison** [comment]
Hi Chris - it's a good question, and as far as I know, there's no particular reason other than "it has worked that way so far".

There's a feature request open for this at #283 that has some thoughts-in-progress.

**Comment by jayaddison** [comment]
Perhaps a slightly better (or more convincing) answer -- although I don't know whether this is genuinely the reason: the [schema.org definition for `Recipe`](https://schema.org/Recipe) includes a `recipeInstructions` field that permits `Text` (single string value) as one of the types.

Based on that, it's fairly predictable and reasonable that some recipe websites fill that schema field with a blob of text - typically newline-separated.

That's my best guess so far at the history of this.

**Comment by Chris230291** [comment]
Right now I `splitlines()` on the instructions and display the list in an `<ol>`.
I just wanted to make sure there wasn't some kind of wired recipe scheme that would break/look bad when displayed like how I am displaying it.

**Comment by jayaddison** [comment]
No problem :+1:

#577 might allow for simplification of your code in future.
