### ISSUE TITLE
BBC GoodFood instructions repeated twice

### ISSUE THREAD

**Issue by TomAFrench** [hhursev/recipe-scrapers#59]
I've noticed that recipes scraped from BBC GoodFood don't properly pull out the instructions. For instance scraping `https://www.bbcgoodfood.com/recipes/herby-spring-chicken-pot-pie` gives them as

> "Heat oven to 200C/180C fan/gas 6. Heat the oil in a large, shallow casserole dish on a medium heat. Add the spring onions and fry for 3 mins, then stir through the frozen spinach and cook for 2 mins or until it\u2019s starting to wilt. Remove the skin from the chicken and discard. Shred the chicken off the bone and into the pan, and discard the bones. Stir through the stock and mustard. Bring to a simmer and cook, uncovered, for 5-10 mins. Stir in the peas, cr\u00e8me fra\u00eeche and herbs, then remove from the heat. Scrunch the filo pastry sheets over the mixture, brush with a little oil and bake for 15-20 mins or until golden brown. MethodHeat oven to 200C/180C fan/gas 6. Heat the oil in a large, shallow casserole dish on a medium heat. Add the spring onions and fry for 3 mins, then stir through the frozen spinach and cook for 2 mins or until it\u2019s starting to wilt. Remove the skin from the chicken and discard. Shred the chicken off the bone and into the pan, and discard the bones. Stir through the stock and mustard. Bring to a simmer and cook, uncovered, for 5-10 mins.Stir in the peas, cr\u00e8me fra\u00eeche and herbs, then remove from the heat. Scrunch the filo pastry sheets over the mixture, brush with a little oil and bake for 15-20 mins or until golden brown. Recipe from Good Food magazine, April 2019"

While I'm here, I've noticed that most of the scrapers pull out just the recipe name, ingredients and instructions. Would contributions of scrapers which extracted more information (e.g. serving size) be accepted?

**Comment by hhursev** [comment]
Thanks for pointing this out! 🍺 

Contribution for serving size will be accepted. Make sure to add method defaulting to 0 in the _abstract.py. However, I can think of extra information that won't be suitable to add in the package (for example rating / difficulty / comments) - those are a no go.
