### ISSUE TITLE
[suggestion] adding type hints

### ISSUE THREAD

**Issue by sbdchd** [hhursev/recipe-scrapers#593]
Would you be open to PRs that add type hints to this repo?

I think we could setup mypy in CI and ignore most of the files and gradually add types over a few PRs.

**Comment by hhursev** [comment]
good idea. Type hints are welcome! Didn't occur to me that we can incorporate in CI and start checking going forward

**Comment by bfcarpio** [comment]
Big fan of adding type hints and I'm excited to see your PRs when you're ready. If you get the CI check in early I think it'd be fine if you add the type hints in chunks as to note make hundreds of PRs or wait on a single PR for editing hundreds of files.

**Comment by sbdchd** [comment]
PR up: https://github.com/hhursev/recipe-scrapers/pull/601

Going with the "ignore existing files" approach -- we can gradually fix / type those files or using something like https://github.com/Instagram/MonkeyType to generate most of the types

**Comment by jayaddison** [comment]
Thanks a lot for adding this @sbdchd :tada:

(I realize we don't have type hints _everywhere_.. but I'm closing this because it seems like that will be an ongoing iterative process, as suggested.  feel free to disagree if we'd like to keep this open as a progress tracker)

**Comment by jayaddison** [comment]
Note: some of the type check failures in #622 seem a bit noisy.  In particular:

```
error: Item "NavigableString" of "Union[Tag, NavigableString]" has no attribute "find_all"  [union-attr]
```

Arguably that's an oddity in BeautifulSoup.  Trying to figure out what we can do about this, while ideally retaining as much type checking as possible from `mypy`.
