### ISSUE TITLE
New site

### ISSUE THREAD

**Issue by diegoferrini** [hhursev/recipe-scrapers#60]
Excellent recipes for Thermomix/Bimby

https://cookidoo.it/
https://cookidoo.it/recipes/recipe/it-IT/r490818

**Comment by marcolussetti** [comment]
When I load the page, the instructions are actually hidden behind a registration screen.

**Comment by jayaddison** [comment]
@diegoferrini Currently `recipe-scrapers` can only easily retrieve content that is public on the web, and all scrapers [should retrieve instructions](https://github.com/hhursev/recipe-scrapers/blob/b23c25c4d21918217fea90e1867bd26ca83f86ae/recipe_scrapers/_abstract.py#L96-L97), since they're an important part of each recipe.

Based on these, cookidoo may be more easily supported by `recipe-scrapers` if they make recipe instructions public in future.

**Comment by Lucki** [comment]
If you can access the HTML - e.g. saved from within your browser - you can use
~~~ python
with open("test.htm", "r") as file:
    scraper = scrape_html(file.read(), 'https://cookidoo.it/recipes/recipe/it-IT/r490818')
~~~

Here's a sample scraper which should work fine.
Manually include it like it's described in the README.

~~~ python
from ._abstract import AbstractScraper
from ._utils import get_minutes, normalize_string, get_yields


class Cookidoo(AbstractScraper):

    @classmethod
    def host(self):
        return 'cookidoo.it'

    def title(self):
        return self.schema.title()

    def total_time(self):
        return self.schema.total_time()

    def yields(self):
        return self.schema.yields()

    def image(self):
        return self.schema.image()

    def ingredients(self):
        return self.schema.ingredients()

    # Only available when logged in
    def instructions(self):
        instructions = self.soup.find(
            'div',
            {'id': 'preparation-steps'}
        ).get_text()

        tricks = self.soup.find(
            'div',
            {'id': 'hints-and-tricks'}
        ).get_text()

        return '\n'.join([
            instructions,
            tricks
        ])

    def ratings(self):
        ratings = self.soup.find(
            'core-rating'
        ).find(
            'span',
            {'class': 'core-rating__counter'}
        )
        return ratings.get_text()
~~~

Tags: Vorwerk Thermomix
