### ISSUE TITLE
Search for random recipe based on ingredients?

### ISSUE THREAD

**Issue by nimaim** [hhursev/recipe-scrapers#607]
First off, thanks for this wonderful library. I was wondering whether this library had the ability to pick a recipe through a certain website (e.g. allrecipes.com) given a list of ingredients. It seems you need to specify a link to a specific recipe in order to parse it, which obviously makes sense, but was wondering if I can modify this library to handle the other case. I am building a CNN model that recognizes some ingredients and want to feed those ingredients into a parser/scraper to get healthy recipes out based on certain criteria (cuisine, calorie count, etc.). Thanks.

**Comment by jayaddison** [comment]
Hi @nimaim - you're welcome.  This library doesn't have any knowledge (state) about the recipes that are available on the web, so as you noticed, it's necessary to provide URL(s) (or HTML) to the the library, and it'll extract recipe information from them.

**Comment by nimaim** [comment]
Thanks for the quick reply @jayaddison! No worries at all, closing this as the purpose of this library does not really fit my use case. I will use something like Selenium then and scrape some things myself. I believe Google recipe results only show those that abide by the JSON-LD format so I should be able to automate pulling some info from this structured format.
