### ISSUE TITLE
Networking code isolation and modularisation

### ISSUE THREAD

**Issue by bfcarpio** [hhursev/recipe-scrapers#658]
Currently, our networking code is defined in the abstract base class. As discussed in #617 I'd like to move remove that code and put as much of it into `scrape_me` as possible.

There have been previous conversations on providing scrapers raw scraped HTML. We can support both workflows if`AbstractScraper` and descendants simply HTML in the constructor. `scrape_me` would be a factory function that abstracts away HTML acquisition and scraper selection (via url mapping)

Goals:

- Maintain an easy to use API for one-off scripts
- Add the ability to override the networking code *or* commit code to better support async workflows
    - This can be `async` python or some advanced task queue support.

Non-goals:

- Eliminate `requests` dependency
    - That's for another issue. Support welcome, but for this particular issue I plan to lift-and-shift the current code.
- Breaking API change where much of this scraper is now using async functions.

Initially, I was thinking of implementing an adapter based system where users could write a function to perform the data request. The default handler would be our current implementation and advanced consumers could override it with an async function or a consumer for a database or task queue. `my_src_handler()` could simply include the HTML and source URL in the returned object without doing any actual work allowing us to accommodate users wanting to scrape arbitrary HTML.

```python
from typing import Callable, Optional

scrape_me(src_handler: Callable[[Optional[str]], [str, str]]=my_src_handler())
```

However, from my quick glance, it seems that calling async from sync functions is difficult and requires managing task queues. Additionally, there would be different infrastructure for running the async handler and the sync handler. Calling sync from async functions is much easier, but may not take advantage of storage client libraries or is wasteful with memory (instantiating many copies of the same client).

Looking for ideas on either writing this implementation in a *sturdier* way or alternative implementations.

Pinging stakeholders @vabene1111 and @NikhilMJain (similar to #472)

**Comment by jayaddison** [comment]
Sounds good @bfcarpio.  I won't add much in the way of technical suggestions, but will share the way I think about how our data extraction works -- I think it matches your HTML constructor abstraction idea.

```
   file ->                            -> parse (for schema queries)            -> query(schema.org-field1)
          -> decode -> select-parser                                 -> model  -> query(schema.org-field2)
network ->                            -> parse (for custom queries)            -> query(custom-field3)
```

And it definitely occurs to me that the dataflows in the library are -- usually -- uni-directional:

1. We start with the raw bytes (and -- very importantly, a URL associated with them), and that yields a decoded stream.
2. We take the URL, and that yields a selected scraper (a set of queries), an ad-hoc parser (`soup`) and a schema parser (`extruct`)
4. We take the decoded stream and feed that to each of the parsers
5. We take the scraper queries and data-loaded parsers, and offer them as a set of object-accessible attributes to the user

The unit tests add a small amount of work at both ends of this: they provide a static mapping of file data to scraper queries (by linking a scraper class to filename(s)), and for each file they also yield a set of expected values, and then assert that the object-accessible attributes match those.

There are some exceptions where scrapers customize the parsing process -- that's fine in practical terms, although possibly also an indication of some kind of design/interface limitation.

All potentially a bit off-topic for the particular task at hand, but I figured it might be worth sharing.

**Comment by hhursev** [comment]
Let's do it with v15. Closing and moving discussion [in the PR](#746)
