### ISSUE TITLE
Some scrapers return results of type list[str] from the 'language' method

### ISSUE THREAD

**Issue by jayaddison** [hhursev/recipe-scrapers#683]
**Context**
This seems to be a bug, discovered during discussion at https://github.com/hhursev/recipe-scrapers/pull/682#discussion_r1026999040.

**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**
Scrapers affected include:
- [`timesofindia`](https://github.com/hhursev/recipe-scrapers/blob/c954e1a087e96d5f0c4350ee2f498a366f56056e/recipe_scrapers/timesofindia.py#L37-L38)
- [`rezeptwelt`](https://github.com/hhursev/recipe-scrapers/blob/c954e1a087e96d5f0c4350ee2f498a366f56056e/recipe_scrapers/rezeptwelt.py#L58-L59)
- [`dr`](https://github.com/hhursev/recipe-scrapers/blob/c954e1a087e96d5f0c4350ee2f498a366f56056e/recipe_scrapers/dr.py#L22-L28)

**The results you expect to see**
This method is intended to return a single string value (generally a BCP-47 language code) -- and we should be able to indicate that with type hints.

**The results (including any Python error messages) that you are seeing**
`mypy` will complain if we attempt to configure a return type for the `language` method that does not contain `list[str]`

**Comment by jayaddison** [comment]
I'm not sure what the best way to handle this is.  A few considerations so far are:

- The [WhatWG HTML specification](https://html.spec.whatwg.org/#attributes-2) says that: "There must never be two or more attributes on the same start tag whose names are an [ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive) match for each other." -- so maybe the type information from `beautifulsoup` is incorrect?
- Adding code to check for list types in the results and then handle those dynamically would be sorta fine and safe, except that it'll be messy code that'll need to be debugged and removed by someone in future - so if we can avoid that future time expenditure, that seems worthwhile

Any ideas / suggestions?

**Comment by hhursev** [comment]
Closing as all these  use soup.find() (that returns 1 element) and then use the element's content attribute to determine language. I don't see how the error might be in the parsers. Will need an example from a recipe where list is returned.
