### ISSUE TITLE
delish.com url import

### ISSUE THREAD

**Issue by mfarazGenetech** [hhursev/recipe-scrapers#694]
**Pre-filing checks**

- [ ] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://www.delish.com/cooking/recipe-ideas/a28608912/butternut-squash-lasagna-recipe/ ...

...

**The results you expect to see**

...

**The results (including any Python error messages) that you are seeing**
I got an issue when i try to import instruction from delish and error showing "'NoneType' object has no attribute 'findAll'" How can i made changes in delish.py to run smoothly
Waiting for your kind response.
Thanks,

...

**Comment by jayaddison** [comment]
Thanks for the report @mfarazGenetech - can you share the version of `recipe-scrapers` that you were using when the error occurred?

**Comment by mfarazGenetech** [comment]
13.5.0

**Comment by jayaddison** [comment]
[Confirmed](https://github.com/hhursev/recipe-scrapers/issues/695#issuecomment-1345864597) that the upgrade fixed this - thanks again for the bug report @mfarazGenetech.

We don't tend to [backport](https://en.wikipedia.org/wiki/Backporting) fixes to earlier versions of the library, so upgrading is probably the recommended solution else who encounters this problem, too.  As a not-really-supported workaround, though, it should also be possible to invoke the schema.org extraction directly for affected pages.
