### ISSUE TITLE
Please Add this link  https://www.bingingwithbabish.com/

### ISSUE THREAD

**Issue by mfarazGenetech** [hhursev/recipe-scrapers#696]
New site : https://www.bingingwithbabish.com/

Please add this site link
Thanks

**Comment by jayaddison** [comment]
Thanks for the suggestion, @mfarazGenetech!  This is a duplicate of #425 - I can't promise when support will be added, but it should be at some point.

A request: when possible, please search for existing bug reports before opening new ones (on this project, and others).

**Comment by mfarazGenetech** [comment]
Thank you so much,  
and sorry for the inconvenience I'll double check existing bug report before opening the new ones.
