### ISSUE TITLE
Should informational lines be included in ingredients?

### ISSUE THREAD

**Issue by jayhale** [hhursev/recipe-scrapers#711]
Consolidating feedback regarding informational lines here, and closing per-scraper feedback (#712).

### Issue

Currently `scraper.ingredients()` includes informational lines that do not represent ingredients.  See below for examples. These lines aren't ingredients, but carry information about preparation, most often by grouping ingredients.

### Possible resolutions

**Group ingredients:** Expose a new `scraper.grouped_ingredients()` that retains the grouping information available from some pages, or defaults to a single group.  Each group could include information such as a title (e.g., `For the Dough`).

**Ignore informational lines:** Spec that scrapers implement `scraper.ingredients()` in a manner that avoids informational lines if at all possible.

### Impacted scrapers

Examples have been identified for these scrapers:

- [seriouseats](https://www.seriouseats.com/new-england-greek-style-pizza)
- [finedininglovers](https://www.finedininglovers.com/recipes/bbq-watermelon-sashimi-secrets-fine-dining)
- [tastykitchen](https://tastykitchen.com/recipes/special-dietary-needs/vegetarian/crunchy-cashew-thai-quinoa-salad-with-ginger-peanut-dressing/)
- [thespruceeats](https://www.thespruceeats.com/baja-fish-tacos-recipe-6829409)
- [theclevercarrot](https://www.theclevercarrot.com/2017/12/how-to-make-sourdough-cinnamon-rolls-step-by-step-guide/)

### Examples

For [https://www.seriouseats.com/new-england-greek-style-pizza](https://www.seriouseats.com/new-england-greek-style-pizza):
```
# Contents of `scrape_me(url).ingredients()`:

For the Dough:                      # Undesired informational line
"400 grams (14 ounces, about 2 1/2
4 grams (about 1 teaspoon) inst...
8 grams (about 1 tablespoon) ko...
2 tablespoons extra virgin oliv...
260 grams (about 1 cup plus 2 t...
For the Sauce:                      # Undesired informational line
2 tablespoons extra virgin oliv...
"2 medium cloves garlic, grated...
1 teaspoon dried oregano
1/4 teaspoon red pepper flakes
3 ounces tomato paste
1 (28-ounce) can crushed tomatoes
Kosher salt
To Assemble:                        # Undesired informational line
"2 tablespoons vegetable shorte...
2 tablespoons extra-virgin oliv...
8 ounces freshly grated whole m...
8 ounces freshly grated white c...
2 ounces Parmigiano-Reggiano
```

For [https://www.finedininglovers.com/recipes/bbq-watermelon-sashimi-secrets-fine-dining](https://www.finedininglovers.com/recipes/bbq-watermelon-sashimi-secrets-fine-dining):
```
# Contents of `scrape_me(url).ingredients()`:
For the Watermelon Sorbet           # Undesired informational line
Watermelon
Lime
Syrup
For the Miso Glazed Watermelon      # Undesired informational line
Watermelon
Dark Miso
Sake
Mirin
Soy Sauce
For the Cured & BBQed Watermelon    # Undesired informational line
Watermelon
Kosher Salt
Smoked paprika
Onion Powder
Ginger Powder
Chili Flakes
# ...
```

**Comment by ggilley** [comment]
I would argue that this is important information to the recipe. It relates the ingredient list to the instructions.

**Comment by jayhale** [comment]
@ggilley agreed. Perhaps this would be better represented as groups of ingredients, since that the semantic intent.  However, I expect the method `.ingredients()` to return *only* ingredients (e.g., can be readily used for questions like "How many ingredients does this recipe have?").

**Comment by ggilley** [comment]
Deciding if something is an ingredient or an informational line is a hard problem. People get very creative in how they express things. I'm not sure it belongs in the scraper itself. Feels like should be later in the pipeline?

**Comment by ggilley** [comment]
A simple way of dealing with them could be to prefix the informational line with a prefix like '# '. That way the ordering is preserved and you have an indicator of the special nature of the line.

**Comment by jayaddison** [comment]
This sounds similar to #301 - the indicated ingredient lines are groupings.

The NIH scraper includes experimental support for an [`IngredientGroup` dataclass](https://github.com/hhursev/recipe-scrapers/blob/93de8afe2d7919e639ab0086b3b99c8c4cc517e0/recipe_scrapers/nihhealthyeating.py#L10-L15) - could that be relevant here too?
