### ISSUE TITLE
[feature] Get list of supported urls

### ISSUE THREAD

**Issue by bjrne** [hhursev/recipe-scrapers#722]
When integrating this into other programs, it would be nice to get a current list of supported urls from this package, ideally even with a flag that shows whether it works by schema or custom parsing. If I am correct, the only way to test this would currently either be hand-parsing the readme or trying the url without and with wild-mode and interpreting the results, right? Or have I missed something?

This library looks very promising, thanks for your work. I would also be willing to implement this and more parsers as well.

**Comment by bfcarpio** [comment]
You're more than welcome to draft a PR to solve this problem. 

You may be able to do some hardcore python and check to see what modules are available in the package at runtime, but that'd only get you the module name as opposed to the URL.

You could also move the `SCRAPERS` global variable dictionary into a function that returns only the dictionary and then wrap that call with `.keys()` etc. 

How you implement it is up to you and we'll be happy to work with you on the PR if you're so inclined.
