### ISSUE TITLE
https://www.hellofresh.at/

### ISSUE THREAD

**Issue by sHooPmyWooP** [hhursev/recipe-scrapers#734]
Please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login), and add sample recipe URL(s) below:

- https://www.hellofresh.at/

This should be equivalent to the already implemented hellofresh.de

**Comment by jayaddison** [comment]
Thanks for the suggestion @sHooPmyWooP!  I've opened a pull request #735 that should hopefully resolve this (and should be able to test that soon).

**Comment by jayaddison** [comment]
This is now available in version [`14.33.0` of `recipe-scrapers` on PyPi](https://pypi.org/project/recipe-scrapers/14.33.0/).
