### ISSUE TITLE
Site: Waitrose recipe directory

### ISSUE THREAD

**Issue by TheBritishSabrina** [hhursev/recipe-scrapers#755]
I've noticed the abstract scraper works on Waitrose recipes but returns the ingredient list as a single character array, e.g. ["1", "", "c", "u", "p", "", "w", "a", "t", "e", "r"]. It'd be great to have these recipes in the standard format instead. Thanks!

- https://www.waitrose.com/home/recipes/recipe_directory/c/chicken_and_broccoli_bake.html
- https://www.waitrose.com/home/recipes/recipe_directory/b/banana__chocolate_and_oatmeal_tea_bread.html

**Comment by jayaddison** [comment]
Note: a fixup (rewrite) for this has been added and is published in [version 14.48.0](https://pypi.org/project/recipe-scrapers/14.48.0/) onwards.
