### ISSUE TITLE
Infinite hang when using wild_mode with scrape_me

### ISSUE THREAD

**Issue by jtarbard** [hhursev/recipe-scrapers#759]
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library (14.36.0)

**The URL of the recipe(s) that are not being scraped correctly**
https://www.coop.co.uk/recipes/frying-pan-pizza
https://www.coop.co.uk/recipes/garlic-and-rosemary-lamb-with-red-wine-gravy

**The results you expect to see**

For the first example:
{
    "@context": "http://schema.org",
    "@type": "Recipe",
    "name": "Frying pan pizza",
    "description" : "Homemade pizza is easier than you think - impress your friends with our quick method",
    "prepTime" : "PT85M",
    "cookTime" : "PT5M",
    ...
}

For the second:
{
    "@context": "http://schema.org",
    "@type": "Recipe",
    "name": "Garlic & rosemary lamb with red wine gravy",
    "description" : "Nailing a classic dish like this is easier than you think — plus it’s a brilliant way to feed a crowd",
    "prepTime" : "PT20M",
    "cookTime" : "PT170M",
    ...
}

**The results (including any Python error messages) that you are seeing**

The program hangs indefinitely when attempting to scrape the website using the wild_mode. Code that reproduces the error:
````
from recipe_scrapers import scrape_me

a = scrape_me("https://www.coop.co.uk/recipes/frying-pan-pizza", wild_mode=True)
````

**Comment by jtarbard** [comment]
Fixed by passing the timeout option and catching the error. Apologies for the unnecessary issue.

**Comment by jayaddison** [comment]
No problem @jtarbard; glad that you were able to find a way to detect and avoid the stall :+1:
