### ISSUE TITLE
Site: https://www.ica.se

### ISSUE THREAD

**Issue by fakethinkpad85** [hhursev/recipe-scrapers#763]
Sample,

- [https:// ...](https://www.ica.se/recept/spaghetti-och-kottfarssas-712805/)

**Comment by jayaddison** [comment]
Sorry, @fakethinkpad85 - I was too brief and unclear with that question.

Recent versions of `recipe-scrapers` have support for the ICA recipe website, so the following should work in Python:

```pycon
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from recipe_scrapers import scrape_me
>>> s = scrape_me('https://www.ica.se/recept/spaghetti-och-kottfarssas-712805/')
>>> s.title()
'Spaghetti och köttfärssås'
>>> s.ingredients()
['500 g nötfärs', '1 gul lök (skalad och hackad)', '2 vitlöksklyftor (skalade och finhackade)', '2 morötter (skalade och rivna)', '2 msk matolja', '1/2 dl tomatpuré', '500 g krossade tomater', '2 dl hönsbuljong', '2 msk kinesisk soja', 'salt och svartpeppar', '4 portioner spaghetti', 'parmesan', 'körsbärstomater']
```

That said, there's always a chance of bugs and problems in the code: please let us know if you find any, and we'll do our best to help.

I haven't had a chance to look into the other issue you opened yet, but will try to soon.

**Comment by fakethinkpad85** [comment]
It seems to all be my bad @jayaddison, after testing again it seems to be working flawlessly. Not sure if i had the link mixed up with another site or if it was just a temporary local fluke. none the less I´m sorry for the late reply.

**Comment by jayaddison** [comment]
No problem - both of those can happen to anyone! - thanks for letting me know, glad to hear that it's working well.
