### ISSUE TITLE
99rezepte.com

### ISSUE THREAD

**Issue by mczeus** [hhursev/recipe-scrapers#765]
Please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login), and add sample recipe URL(s) below:

- https://99rezepte.com/hackbraten-supersaftig-saftiger-hackbraten-mit-viel-sose/

**Comment by derteufelqwe** [comment]
After taking a look at this website, I think it's not possible to parse it. 
It doesn't contain any schema so we would need to parse the HTML. But the HTML is highly unstructured and there is no way to distinguish between ingredients and steps.

**Comment by jayaddison** [comment]
I agree with @derteufelqwe's view on this.  Since it doesn't seem feasible to support at the moment, I'm going to close this as not-planned so that we have the history of the problem but do not see it on our available task list.

**Comment by jayaddison** [comment]
(thank you for the report anyway @mczeus - sorry that it isn't feasible to support this)
