### ISSUE TITLE
One particular recipe using scrape_me in wild mode returns ingredients as a list of single characters

### ISSUE THREAD

**Issue by beardedbritboston** [hhursev/recipe-scrapers#767]
**Pre-filing checks**

- [ x] I have searched for open issues that report the same problem
- [  x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**
https://usapears.org/recipe/sauteed-bosc-pears/
test script:
`from recipe_scrapers import scrape_me

u = 'https://usapears.org/recipe/sauteed-bosc-pears/'
scraper = scrape_me(u, wild_mode=True)
print(scraper.ingredients())
exit(0)
`
...

**The results you expect to see**
a list of 8 ingredients as per web page
...

**The results (including any Python error messages) that you are seeing**
['2', '', 't', 'a', 'b', 'l', 'e', 's', 'p', 'o', 'o', 'n', 's', '', 'b', 'u', 't', 't', 'e', 'r', '', '¼', '', 't', 'e', 'a', 's', 'p', 'o', 'o', 'n', '', 'c', 'i', 'n', 'n', 'a', 'm', 'o', 'n', '', '¼', '', 't', 'e', 'a', 's', 'p', 'o', 'o', 'n', '', 'g', 'r', 'o', 'u', 'n', 'd', '', 'n', 'u', 't', 'm', 'e', 'g', '', '¼', '', 't', 'e', 'a', 's', 'p', 'o', 'o', 'n', '', 'g', 'r', 'o', 'u', 'n', 'd', '', 'a', 'l', 'l', 's', 'p', 'i', 'c', 'e', '', '6', '', 'B', 'o', 's', 'c', '', 'U', 'S', 'A', '', 'P', 'e', 'a', 'r', 's', ',', '', 'p', 'e', 'e', 'l', 'e', 'd', ',', '', 'c', 'o', 'r', 'e', 'd', ',', '', 'a', 'n', 'd', '', 'q', 'u', 'a', 'r', 't', 'e', 'r', 'e', 'd', '', 'J', 'u', 'i', 'c', 'e', '', 'o', 'f', '', '½', '', 'l', 'e', 'm', 'o', 'n', '', '(', 'a', 'b', 'o', 'u', 't', '', '3', '', 't', 'a', 'b', 'l', 'e', 's', 'p', 'o', 'o', 'n', 's', ')', '', '1', '', '½', '', 'c', 'u', 'p', '', 'n', 'o', 'n', 'f', 'a', 't', '', 'v', 'a', 'n', 'i', 'l', 'l', 'a', '', 'y', 'o', 'g', 'u', 'r', 't', '', 'o', 'r', '', 'f', 'r', 'o', 'z', 'e', 'n', '', 'y', 'o', 'g', 'u', 'r', 't', '', '½', '', 'c', 'u', 'p', '', 'c', 'h', 'o', 'p', 'p', 'e', 'd', ',', '', 't', 'o', 'a', 's', 't', 'e', 'd', '', 'C', 'a', 'l', 'i', 'f', 'o', 'r', 'n', 'i', 'a', '', 'w', 'a', 'l', 'n', 'u', 't', 's']

...

**Comment by jayaddison** [comment]
Confirmed: this bug existed before d5e64004a01d6059185ebb45c36e4071b025e98c, and is fixed by that same change.

**Comment by hhursev** [comment]
Works after https://github.com/hhursev/recipe-scrapers/commit/d5e64004a01d6059185ebb45c36e4071b025e98c (don't use wild_mode=True with usepears.org)
