### ISSUE TITLE
Trello

### ISSUE THREAD

**Issue by TheDeluxeThrowaway** [hhursev/recipe-scrapers#773]
Was wondering if it was possible to support trello here's a test recipe https://trello.com/c/sIPEC3Ze/22-frijoles-de-olla-by-mi-cocina

**Comment by jayaddison** [comment]
Hey @TheDeluxeThrowaway - do you know whether recipes on Trello boards use a standard HTML format?

In other words: for multiple different Trello boards created by multiple different people, can we rely on the structure of the webpage to extract recipe information from the same place(s) across all of the boards?

**Comment by TheDeluxeThrowaway** [comment]
@jayaddison Sorry I didn't grow up during the myspace era so I don't know about the html 

I mean generally it should all be the same right Title for Title, Checklist for ingredient list, body for body. Comments would be the only thing I could see being wonky since that could be either recipe notes or comments about the recipe itself but outside of that I don't see why anyone would do any overly weird things with formatting. But who knows people are weird

**Comment by jayaddison** [comment]
Hehe, no problem :)

What's your level of familiarity with Python programming?

**Comment by TheDeluxeThrowaway** [comment]
Novice but I am a master at googlefu and have coder friends with no lives

**Comment by jayaddison** [comment]
Well, thanks for tolerating us.  I'd bet that within ~60 minutes you could develop a Python script to retrieve the main headline from your preferred news website, and a unit test that fails if the HTML element containing the headline isn't found.

**Comment by TheDeluxeThrowaway** [comment]
Can you show me an example of both a headline and unit test @jayaddison so I know I'm looking at the right thing?
