### ISSUE TITLE
Hellofresh parser fails ingredients.

### ISSUE THREAD

**Issue by orjen** [hhursev/recipe-scrapers#777]
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://www.hellofresh.com/recipes/chakchouka-au-fromage-de-chevre-5eb41aa7d5418a482a67b864
- https://www.hellofresh.dk/recipes/mexicansk-inspireret-rejebowl-64477224056ea22332c15bab
...

**The results you expect to see**

>['1 pièce(s) Oignon', "2 pièce(s) Gousse d'ail", '0.5 pièce(s) Piment', '1 pièce(s) Poivron rouge', '4 pièce(s) Tomate', '5 g Persil', '4 pièce(s) Œuf', '75 g Fromage de chèvre frais', '2 pièce(s) Baguette', "1 cs Huile d'olive", '½ pièce(s) Cube de bouillon de légumes', 'selon le goût Poivre et sel']

>['150 g Basmatiris', '150 g Rejer', '5 g Tex-Mex', '1 stk Avocado', '150 g Yoghurt', '½ stk Lime', '20 g Saltede peanuts', '1 g Chiliflager', '1 stk Tomat', '½ stk Rødløg', '1 pose Koriander', '2 g Ay Cajun-ba', '3 dl Vand (trin 1)', '½ tsk Salt (trin 1)', '¼ tsk Salt (trin 2)', '1 spsk Olivenolie (trin 3)', '½ tsk Sukker (trin 3)', '1 spsk Smør (trin 5)', '1 spsk Vand (trin 5)', '½ spsk Olivenolie (trin 5)']

**The results (including any Python error messages) that you are seeing**

```
url = 'https://www.hellofresh.com/recipes/chakchouka-au-fromage-de-chevre-5eb41aa7d5418a482a67b864'

scraper = scrape_me(url)

scraper.ingredients()
```
>['2 * 1 pièce(s) Oignon', "2 * 2 pièce(s) Gousse d'ail", '2 * ½ pièce(s) Piment', '2 * 1 pièce(s) Poivron rouge', '2 * 4 pièce(s) Tomate', '2 * 5 g Persil', '2 * 4 pièce(s) Œuf', '2 * 75 g Fromage de chèvre frais', '2 * 2 pièce(s) Baguette', "2 * 1 cs Huile d'olive", '2 * ½ pièce(s) Cube de bouillon de légumes', '2 * selon le goût Poivre et sel']

```
url2 = 'https://www.hellofresh.dk/recipes/mexicansk-inspireret-rejebowl-64477224056ea22332c15bab'

scraper2 = scrape_me(url2)

scraper2.ingredients()
```

>['2 * 150 g Basmatiris', '2 * 150 g Rejer', '2 * 5 g Tex-Mex', '2 * 1 stk Avocado', '2 * 150 g Yoghurt', '2 * ½ stk Lime', '2 * 20 g Saltede peanuts', '2 * 1 g Chiliflager', '2 * 1 stk Tomat', '2 * ½ stk Rødløg', '2 * 1 pose Koriander', '2 * 2 g Ay Cajun-ba', '2 * 3 dl Vand (trin 1)', '2 * ½ tsk Salt (trin 1)', '2 * ¼ tsk Salt (trin 2)', '2 * 1 spsk Olivenolie (trin 3)', '2 * ½ tsk Sukker (trin 3)', '2 * 1 spsk Smør (trin 5)', '2 * 1 spsk Vand (trin 5)', '2 * ½ spsk Olivenolie (trin 5)']
...

In case you'd like to switch to html scrapes instead of the schema ones, here are some bs4 useful selectors

```
ingredients_shipped = soup.select('div[data-test-id="ingredient-item-shipped"]')
ingredients_not_shipped = soup.select('div[data-test-id="ingredient-item-not-shipped"]')

nutrition = soup.select('div[data-test-id="items-per-serving"]')[0].findAll('span')

recipe_steps = soup.select('div[data-test-id="instruction-step"]')
```

**Comment by strangetom** [comment]
This looks quite simple to fix. The changes added to the HelloFresh scraper due to #527 are not need anymore because the yield and ingredient quantities in the embedded data are consistent.

**Comment by gloriousDan** [comment]
Great, it seems that only one year and a bit after my bug report they fixed it. I didn't think that it would happen :)
