### ISSUE TITLE
Madsvin.com

### ISSUE THREAD

**Issue by JohnnyJTH** [hhursev/recipe-scrapers#780]
Some recipes on there have multiple "substeps". For example the second link has two "substeps", "Æbleskivedejen" and "Bagning af Æbleskiver". 

- https://madsvin.com/pandekager/
- https://madsvin.com/aebleskiver-opskrift/

**Comment by jayaddison** [comment]
This site is now available in [version 14.41.0 of the library on PyPi](https://pypi.org/project/recipe-scrapers/).
