### ISSUE TITLE
vegetarbloggen.no

### ISSUE THREAD

**Issue by magnulu** [hhursev/recipe-scrapers#790]
Schema available

- https://www.vegetarbloggen.no/2021/11/25/pasta-i-gresskarsaus-2/
- https://www.vegetarbloggen.no/2023/05/03/blomkalsuppe-med-hvite-bonner/

**Comment by jayaddison** [comment]
This site is now available in [version 14.41.0 of the library on PyPi](https://pypi.org/project/recipe-scrapers/).
