### ISSUE TITLE
Recipes from Costco.com

### ISSUE THREAD

**Issue by mattboutte** [hhursev/recipe-scrapers#848]
Example recipe: [https://www.costco.com/connection-recipe-chicken-salad-grapes-walnuts-blue-cheese-march-2023.html](https://www.costco.com/connection-recipe-chicken-salad-grapes-walnuts-blue-cheese-march-2023.html)

When attempting to scrape, it doesn't error out. It just keeps attempting.

**Comment by jayaddison** [comment]
This is now available in version 14.46.0 - thank you, @jknndy!
