### ISSUE TITLE
SSL error message during scraper creation

### ISSUE THREAD

**Issue by jknndy** [hhursev/recipe-scrapers#851]
**Pre-filing checks**

- [X] I have searched for open issues that report the same problem
- [X] I have checked that the bug affects the latest version of the library

## Description

While trying to generate a scraper for `https://recipes.sparkpeople.com` I am receiving an SSL Certification Verification error. 
Scraper requested in #849

## Traceback

\`\`\`
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
...
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='recipes.sparkpeople.com', port=443): Max retries exceeded with url: /recipe-detail.asp?recipe=198343 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))
...
requests.exceptions.SSLError: HTTPSConnectionPool(host='recipes.sparkpeople.com', port=443): Max retries exceeded with url: /recipe-detail.asp?recipe=198343 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))
\`\`\`

## Steps to Reproduce

1. Run the `generate.py` script with the following URL as the target: `https://recipes.sparkpeople.com/recipe-detail.asp?recipe=198343`

## Notes
Also attempt to generate on the v15 branch after seeing mention of a similar issue being resolved in that branch.

**Comment by strangetom** [comment]
This looks like a problem with the website's SSL certificate - the certificate chain is incomplete. See http://www.sslchecker.com/sslchecker?su=fda0dc61e803836b3e553d400a3f4fc4.

I don't recommend we try to work around this problem here.
We could still develop the scraper, but it wouldn't work until the site fixes it's SSL certificate, so we might be better waiting until then.

**Comment by jknndy** [comment]
@strangetom Thanks! 

I'll close this issue for now and make note on the scraper request issue
