### ISSUE TITLE
Bon Appetit Errors

### ISSUE THREAD

**Issue by jbelluch** [hhursev/recipe-scrapers#889]
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://https://www.bonappetit.com/recipe/lemony-braised-chicken-legs-and-tomatoes

...

**The results you expect to see**
Previously been using the scraper with no issue (like 2 days ago), but when going to scrape Bon Appetit, I'm getting a bunch of errors as if they changed everything. Having trouble figuring out how to fix it.
...

**The results (including any Python error messages) that you are seeing**

recipe = scrape_me('https://www.bonappetit.com/recipe/lemony-braised-chicken-legs-and-tomatoes')
recipe.title()
Traceback (most recent call last):
  File "<pyshell#64>", line 1, in <module>
    recipe.title()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/recipe_scrapers/plugins/exception_handling.py", line 64, in decorated_method_wrapper
    return decorated(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/recipe_scrapers/plugins/html_tags_stripper.py", line 75, in decorated_method_wrapper
    decorated_func_result = decorated(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/recipe_scrapers/plugins/normalize_string.py", line 34, in decorated_method_wrapper
    return normalize_string(decorated(self, *args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/recipe_scrapers/plugins/schemaorg_fill.py", line 48, in decorated_method_wrapper
    return decorated(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/recipe_scrapers/bonappetit.py", line 11, in title
    return self.schema.title()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/recipe_scrapers/_schemaorg.py", line 80, in title
    return normalize_string(self.data.get("name"))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/recipe_scrapers/_utils.py", line 141, in normalize_string
    unescaped_string = html.unescape(string)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/html/__init__.py", line 130, in unescape
    if '&' not in s:
TypeError: argument of type 'NoneType' is not iterable
...

**Comment by jknndy** [comment]
Hi @jbelluch, I can confirm that this scraper is no longer working. It does appear like they've revamped the whole structure of the site which caused it.

I'll be taking a look at this sometime this week (unless someone beats me to it) and i'll ping you with an update.

**Comment by jbelluch** [comment]
Thanks! I'm a hobby programmer over here, so I just got some time tonight and have been digging into it to see if I can figure it out. I'm not savvy enough to use the git functions, but I'll share any files I tinker with here to hopefully help

**Comment by jbelluch** [comment]
@jknndy Alright, I gave it a go and it appears to work for the few test cases I've done. Feel like the code is probably clunky though. hopefully this helps!
[bonappetit.py.zip](https://github.com/hhursev/recipe-scrapers/files/12842722/bonappetit.py.zip)

**Comment by jbelluch** [comment]
Updated slightly, put in a condition to remove space in front of ingredients that don't have quantity. I ran this through a backlog of recipes I had from bonappetit and it is looking good. Are there other scrapers that preserve ingredient headers, like these ingredients for sauce, these for chicken, etc? I don't remember it previously having that functionality, but noticed one of my test cases had it and the scraper just flattens it into one list and couldn't remember how it was handled previously.

Thanks!

`# mypy: disallow_untyped_defs=False
from ._abstract import AbstractScraper
import re


class BonAppetit(AbstractScraper):
    @classmethod
    

    def host(cls):
        return "bonappetit.com"

    def title(self):
        title = self.soup.find("h1", {'data-testid' : 'ContentHeaderHed'}).get_text()
        return title

    def total_time(self):
        return None

    def yields(self):
        ingredientContent = self.soup.find("div", {'data-testid' : 'IngredientList'})
        yield_search = re.compile('.*Yield-.*')
        yield_section = ingredientContent.find('p', {'class': yield_search})
        yield_value = yield_section.get_text()
        words = yield_value.split()
        words = [word.capitalize() for word in words]
        if len(words) > 2:
            list_formatted = words[-2:]
            yield_value = " ".join(list_formatted)
        else:
            yield_value = " ".join(words)
        return yield_value

    def ingredients(self):
        ingredientList = self.soup.find("div", {'data-testid' : 'IngredientList'})

        list_search = re.compile('List-.*')

        ingredients_section =ingredientList.find('div', {'class': list_search})

        amount_search = re.compile('Amount-.*')
        amounts = ingredients_section.findAll('p', {'class': amount_search})
        amounts = [item.get_text() for item in amounts]

        description_search = re.compile('Description-.*')
        descriptions = ingredients_section.findAll('div', {'class': description_search})
        descriptions = [item.get_text() for item in descriptions]

        index = 0
        ingredients =[]
        while index < len(descriptions):
            if amounts[index] == '':
                line_item = descriptions[index]
            else:
                line_item = amounts[index] + " " + descriptions[index]
            ingredients.append(line_item)
            index = index + 1

        return ingredients
    
    def instructions(self):
        direction_search = re.compile('InstructionGroupWrapper-.*')
        directionSection = self.soup.find("ol", {'class' : direction_search})
        directionList = directionSection.findAll('p')
        directionList = [item.get_text() for item in directionList]
        instructionText = "\n".join(directionList)
        return instructionText
`

**Comment by jknndy** [comment]
Hey @jbelluch, could you check if this is still broken? I just went to work on it and everything seems to be working, wonder if it was a temporary change on their end. Let me know!

**Comment by jbelluch** [comment]
Well that's annoying, but good i guess! Yeah just reverted my version back and it still works. My work around still worked as well, so they must have just added the schema support back. I'll close this then, thanks for checking!
