### ISSUE TITLE
elavegan.com

### ISSUE THREAD

**Issue by dbluxo** [hhursev/recipe-scrapers#906]
Please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login), and add sample recipe URL(s) below:

- https://elavegan.com/vegan-lentil-bolognese/
- https://elavegan.com/red-lentil-dahl/

**Comment by jayaddison** [comment]
Support for this site is available in version 14.52.0 - thanks for the request @dbluxo!
