### ISSUE TITLE
Store recipe link itself in object

### ISSUE THREAD

**Issue by wassupluke** [hhursev/recipe-scrapers#935]
When using your code in my project I'm running into a situation where it would be gloriously helpful to have the link that was scraped (the link to the recipe itself) stored in the object for easier retrieval. e.g. I don't want to have to make another list just to keep track of what object belongs to what link, I want to be able to pull the link right from the object.

**Comment by jayaddison** [comment]
Hey @wassupluke - OK, I think I see what you mean - could you confirm that `recipe.canonical_url()` _isn't_ what you're after here?

Maybe something like `recipe.requested_url()` would be it?  (so for `recipe = scrape_me(url)`, `recipe.requested_url() == url`)

**Comment by wassupluke** [comment]
Oh that's it! Can we add that info to the README for others to find?

**Comment by jayaddison** [comment]
Sure thing - done!  Note that `canonical_url` isn't _guaranteed_ to be available - for some websites it isn't available in the HTML.  So, depending on how you're using it, and for which sites, you might be OK with that, or there could be some edge cases.
