### ISSUE TITLE
Feature request: get list of recipes

### ISSUE THREAD

**Issue by pineapplelogic174** [hhursev/recipe-scrapers#936]
Hi all,

How are you currently obtaining a list of recipes available from a particular site?

I see you can use the "scrape_me" method to retrieve recipe data from a particular recipe's URL. But that would require knowledge of the URL in advance.

My use case was to iterate through multiple recipes to find things I wanted. Is there any method available to obtain a list of recipe URLs at present?

Thanks!

**Comment by jayaddison** [comment]
Hi @pineapplelogic174 - yep, that's correct: this library provides the ability to read from an input URL and to attempt to extract recipe information from the resulting page data.  We don't have a way to emit a directory/list of the recipes contained on a given website though, nope.
