### ISSUE TITLE
New website https://www.ricetteperbimby.it/ricette/cottage-pie-bimby

### ISSUE THREAD

**Issue by StefanoGiu** [hhursev/recipe-scrapers#947]
Please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login), and add sample recipe URL(s) below:

- https://www.ricetteperbimby.it/ricette/cottage-pie-bimby

**Comment by jknndy** [comment]
Hi @StefanoGiu,

I've completed the adjustments needed to add full support for this site but they won't be merged until after #944 is. For the time being this site contains all of the data in the schema format which means it can be retrieved by using wild_mode.

```python
from recipe_scrapers import scrape_me
scraper = scrape_me('https://www.ricetteperbimby.it/ricette/cottage-pie-bimby', wild_mode=True)
scraper.title()
scraper.instructions()  # etc.
```

I'll close this issue once the full functionality is implemented.
