### ISSUE TITLE
Issue getting ingredients from www.yummly.com

### ISSUE THREAD

**Issue by dips83** [hhursev/recipe-scrapers#951]
Getting no ingredients when scraping recipe from yummly.com

Recipe example:

https://www.yummly.com/recipe/Perfectly-Baked-Salmon-2389564

It also has recipe groups so support for that should be added as well.

**Comment by hhursev** [comment]
Sorry, this seems to be an issue related with bot protection from yummly. This package is not suitable for bypassing such. Closing and marking the yummly scraper as offline use only in the README.
