### ISSUE TITLE
Scraping recipes that have a yields of `3 dozen` results in a yields of `3 servings`

### ISSUE THREAD

**Issue by sbdchd** [hhursev/recipe-scrapers#960]
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

If a recipe has a yield in the `json+ld` of `About 3 dozen`, then the `get_yields` function in the utils will end up returning `3 servings` instead of `About 3 dozen`

**Comment by jknndy** [comment]
hey @sbdchd, thanks for the bug report! Could you please provide an example URL that was returning this?

**Comment by sbdchd** [comment]
https://cooking.nytimes.com/recipes/1020665-potato-chip-chocolate-chip-cookies
