### ISSUE TITLE
dietdoctor.com

### ISSUE THREAD

**Issue by beasthouse-au** [hhursev/recipe-scrapers#966]
Please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login), and add sample recipe URL(s) below:

- https://www.dietdoctor.com/recipes/keto-tuna-burgers
- https://www.dietdoctor.com/recipes/keto-pizza-omelet
- https://www.dietdoctor.com/recipes/low-carb-flank-steak-with-pepper-sauce-and-cauliflower-and-broccoli-gratin

Loads of good, healthy recipes here that I would love to be able to scrape into Mealie, hoping you are able to support this request.

The layout for their system is as follows:

```yaml
{
  "@type": "HowToSection",
  "name": "Instructions",
  "itemListOrder": "Ascending",
  "numberOfItems": 3,
  "itemListElement": [
    {
      "@type": "HowToStep",
      "position": "1",
      "itemListElement": {
        "@type": "HowToDirection",
        "position": "1",
        "text": "Mix the ingredients together (minus the oil) in a medium-sized bowl. Shape the mixture into small burgers, about 2 inches (5 cm) wide and 0.4 inch (1 cm) thick."
      }
    },
  ]
}
```

Mealie does support the systen down to the HowToStep where Mealie does expect an text field instead of another dict of the HowToDirection Type.

Was encouraged to raise a request with you to support this.

**Comment by jknndy** [comment]
Hi @beasthouse-au, thanks for the bug report! 

Functionality to support websites that use this type of instruction listing was added in version [14.53.0](https://github.com/hhursev/recipe-scrapers/releases/tag/14.53.0) via wild_mode (wont be listed in the supported sites list but should function as expected). 

It appears that the mealie library is running 14.52.0, I'd let a maintainer of the mealie project know that an updating the dependency should fix it!
