### ISSUE TITLE
www.mundodereceitasbimby.com.pt - Mundo de Receitas Bimby

### ISSUE THREAD

**Issue by GoganGogan** [hhursev/recipe-scrapers#967]
Biggest Portuguese Thermomix/Bimby community based recipe site. Would love to see it integrated.

Thank you! 

https://www.mundodereceitasbimby.com.pt/pratos-principais-carne-receitas/empadao-de-carne/eyfdj0p4-6f492-762035-cfcd2-j1gkapa1...
https://www.mundodereceitasbimby.com.pt/pratos-principais-peixe-receitas/arroz-de-polvo/3mg2kqd2-6f492-480172-cfcd2-amfsdqbu
https://www.mundodereceitasbimby.com.pt/sobremesas-receitas/arroz-doce/s3i4dif3-6f492-649128-cfcd2-ivigqkm9
https://www.mundodereceitasbimby.com.pt/entradas-receitas/aperitivos-de-sementes-de-sesamo-e-papoila/6hctbzk9-7de6c-203618-cfcd2-pdqwfwk4
https://www.mundodereceitasbimby.com.pt/bolos-e-biscoitos-receitas/delicia-de-chocolate/5dxkmnsj-6f492-271549-cfcd2-f1cql72v

**Comment by jayaddison** [comment]
This is now available in [version 14.54.0](https://pypi.org/project/recipe-scrapers/14.54.0/), also published PyPi.  Thanks for the suggestion!

**Comment by GoganGogan** [comment]
Thank you!
