### ISSUE TITLE
Kitchen Sanctuary Scraper

### ISSUE THREAD

**Issue by geoff-driskell** [hhursev/recipe-scrapers#971]
Please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login), and add sample recipe URL(s) below:

- https://www.kitchensanctuary.com/honey-garlic-chicken/
- https://www.kitchensanctuary.com/easy-chicken-lo-mein/

**Comment by jknndy** [comment]
Hi @geoff-driskell, you're on the right track! Opening an issue here is one way to show that you are actively working on a scraper addition. Another route would be to open a draft Pull Request with your in progress code so that other contributors can review the code once it is ready to be added.

**Comment by jayaddison** [comment]
This has been implemented by #1115 (thank you, @Mooree003) and should appear in an upcoming release of `recipe-scrapers` on PyPi soon (within the next week or so).
