### ISSUE TITLE
Mob: request (new website design?)

### ISSUE THREAD

**Issue by jacksgreen** [hhursev/recipe-scrapers#972]
https://www.mob.co.uk/recipes/roasted-tomato-spaghetti-soup
https://www.mob.co.uk/recipes/speedy-udon-miso-noodle-soup

**Comment by jayaddison** [comment]
This is now available in [version 14.54.0](https://pypi.org/project/recipe-scrapers/14.54.0/), also published PyPi. (thanks for both the report and the fix!)
