### ISSUE TITLE
New scraper for www.StrongrFaster.com

### ISSUE THREAD

**Issue by cgranum** [hhursev/recipe-scrapers#978]
Looking for a scraper for www.StrongerFastr.com.
An example recipe is: https://www.strongrfastr.com/recipes/96-latininspired_creamy_chicken_stew

Thank you!

**Comment by jayaddison** [comment]
Thanks @cgranum for the suggestion - this is now available in [version 14.54.0](https://pypi.org/project/recipe-scrapers/14.54.0/) of the library.
