### ISSUE TITLE
mob.co.uk: empty ingredient groups for recipes that don't have ingredient section headings

### ISSUE THREAD

**Issue by jayaddison** [hhursev/recipe-scrapers#987]
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://www.mob.co.uk/recipes/speedy-udon-miso-noodle-soup

**The results you expect to see**

Although not all recipes provide groupings/section headings for the ingredients, we do want the output of `scraper.ingredient_groups` to include a complete list of ingredients in all cases.

That means that for recipes without grouped ingredients, there should be a single placeholder grouping with `purpose=None`.

(there's some further information on this in the [ingredient group developer documentation](https://github.com/hhursev/recipe-scrapers/blob/main/docs/in-depth-guide-ingredient-groups.md))

**The results (including any Python error messages) that you are seeing**

Calling the `.ingredient_groups()` method on the scraper produces an empty list.

cc @jacksgreen

**Comment by jacksgreen** [comment]
@jayaddison I've create a pull request fixing this issue

**Comment by jayaddison** [comment]
Thanks @jacksgreen!  I've added one suggested edit; apart from that it looks good - it'll be nice to have this fixed.
