### ISSUE TITLE
Recept.se

### ISSUE THREAD

**Issue by pricken45** [hhursev/recipe-scrapers#993]
Please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login), and add sample recipe URL(s) below:

- https://recept.se/recept/chokladbollar-grundrecept

**Comment by jayaddison** [comment]
This is now available in [version 14.54.0](https://pypi.org/project/recipe-scrapers/14.54.0/), also published PyPi.  Thank you for the suggestion (and thanks to @jknndy for the implementation!).
